[21:02:13.321] startujem server, seed je 3630260670
main: prepisujem zaznamovy adresar: zaznamy/000007
[21:02:13.321] restartujem klienta bubokrki
[21:02:13.321] restartujem klienta paulinia
[21:02:13.321] restartujem klienta m
[21:02:13.322] restartujem klienta jedejedemasinka
tah 0
hrac 0'DOWN'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 3'RIGHT'
tah 1
hrac 2'DOWN'
hrac 3'RIGHT'
hrac 0'UP'
hrac 1'LEFT'
tah 2
hrac 2'DOWN'
hrac 3'RIGHT'
hrac 0'RIGHT'
hrac 1'UP'
tah 3
hrac 2'RIGHT'
hrac 3'UP'
hrac 0'UP'
hrac 1'UP'
tah 4
hrac 2'RIGHT'
hrac 3'LEFT'
hrac 0'DOWN'
hrac 1'RIGHT'
tah 5
hrac 2'RIGHT'
hrac 3'LEFT'
hrac 0'UP'
hrac 1'RIGHT'
tah 6
hrac 2'RIGHT'
hrac 3'RIGHT'
hrac 0'UP'
hrac 1'RIGHT'
tah 7
hrac 2'UP'
hrac 3'UP'
hrac 0'UP'
hrac 1'RIGHT'
tah 8
hrac 2'UP'
hrac 3'LEFT'
hrac 0'LEFT'
hrac 1'DOWN'
tah 9
hrac 2'LEFT'
hrac 3'UP'
hrac 0'DOWN'
hrac 1'DOWN'
tah 10
hrac 2'LEFT'
hrac 3'LEFT'
hrac 0'LEFT'
hrac 1'DOWN'
tah 11
hrac 3'LEFT'
hrac 0'DOWN'
hrac 1'RIGHT'
hrac 2'LEFT'
tah 12
hrac 2'LEFT'
hrac 3'LEFT'
hrac 0'LEFT'
hrac 1'RIGHT'
tah 13
hrac 2'LEFT'
hrac 3'DOWN'
hrac 0'LEFT'
hrac 1'DOWN'
tah 14
hrac 2'DOWN'
hrac 3'DOWN'
hrac 0'LEFT'
hrac 1'DOWN'
tah 15
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'DOWN'
hrac 1'LEFT'
tah 16
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'LEFT'
hrac 1'DOWN'
tah 17
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'UP'
hrac 1'LEFT'
tah 18
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'UP'
hrac 1'LEFT'
tah 19
hrac 2'RIGHT'
hrac 3'LEFT'
hrac 0'RIGHT'
hrac 1'UP'
hrac 1 bol zabity hracom 3
proces 28840 umrel na: Terminated
write: pid -1: Bad file descriptor
tah 20
hrac 2'RIGHT'
hrac 3'UP'
hrac 0'UP'
tah 21
hrac 2'UP'
hrac 3'LEFT'
hrac 0'LEFT'
tah 22
hrac 2'UP'
hrac 3'LEFT'
hrac 0'LEFT'
tah 23
hrac 2'UP'
hrac 3'DOWN'
hrac 0'UP'
tah 24
hrac 2'RIGHT'
hrac 3'RIGHT'
hrac 0'UP'
tah 25
hrac 2'RIGHT'
hrac 3'DOWN'
hrac 0'LEFT'
tah 26
hrac 2'DOWN'
hrac 3'RIGHT'
hrac 0'DOWN'
tah 27
hrac 2'DOWN'
hrac 3'RIGHT'
hrac 0'LEFT'
tah 28
hrac 2'DOWN'
hrac 3'RIGHT'
hrac 0'LEFT'
tah 29
hrac 2'LEFT'
hrac 3'RIGHT'
hrac 0'DOWN'
tah 30
hrac 2'LEFT'
hrac 3'RIGHT'
hrac 0'DOWN'
tah 31
hrac 2'RIGHT'
hrac 3'RIGHT'
hrac 0'DOWN'
tah 32
hrac 2'RIGHT'
hrac 3'RIGHT'
hrac 0'RIGHT'
tah 33
hrac 2'RIGHT'
hrac 3'UP'
hrac 0'RIGHT'
tah 34
hrac 2'LEFT'
hrac 3'UP'
hrac 0'RIGHT'
tah 35
hrac 2'UP'
hrac 3'UP'
hrac 0'DOWN'
tah 36
hrac 2'RIGHT'
hrac 3'UP'
hrac 0'DOWN'
tah 37
hrac 2'DOWN'
hrac 3'DOWN'
hrac 0'RIGHT'
tah 38
hrac 2'RIGHT'
hrac 3'UP'
hrac 0'RIGHT'
tah 39
hrac 2'UP'
hrac 3'RIGHT'
hrac 0'RIGHT'
tah 40
hrac 2'UP'
hrac 3'RIGHT'
hrac 0'RIGHT'
tah 41
hrac 2'LEFT'
hrac 3'RIGHT'
hrac 0'UP'
tah 42
hrac 2'LEFT'
hrac 3'DOWN'
hrac 0'LEFT'
proces 28839 umrel na: Floating point exception
tah 43
[21:02:16.180] restartujem klienta bubokrki
zabi/kill: pid 28839: No such process
hrac 2'UP'
hrac 3'DOWN'
proces 28843 umrel na: Floating point exception
hrac 0 bol zabity hracom 0
zabi/kill: pid 28843: No such process
tah 44
hrac 2'RIGHT'
hrac 3'RIGHT'
tah 45
hrac 2'RIGHT'
hrac 3'UP'
tah 46
hrac 2'RIGHT'
hrac 3'LEFT'
tah 47
hrac 2'RIGHT'
hrac 3'DOWN'
tah 48
hrac 2'DOWN'
hrac 3'DOWN'
tah 49
hrac 2'DOWN'
hrac 3'DOWN'
tah 50
hrac 2'DOWN'
hrac 3'DOWN'
tah 51
hrac 2'RIGHT'
hrac 3'DOWN'
tah 52
hrac 2'RIGHT'
hrac 3'RIGHT'
tah 53
hrac 2'RIGHT'
hrac 3'DOWN'
tah 54
hrac 2'RIGHT'
hrac 3'LEFT'
tah 55
hrac 2'UP'
hrac 3'LEFT'
tah 56
hrac 2'LEFT'
hrac 3'DOWN'
tah 57
hrac 2'LEFT'
hrac 3'RIGHT'
tah 58
hrac 2'LEFT'
hrac 3'RIGHT'
tah 59
hrac 2'UP'
hrac 3'RIGHT'
tah 60
hrac 2'UP'
hrac 3'UP'
tah 61
hrac 2'UP'
hrac 3'UP'
tah 62
hrac 2'LEFT'
hrac 3'UP'
tah 63
hrac 2'LEFT'
hrac 3'LEFT'
tah 64
hrac 2'LEFT'
hrac 3'UP'
tah 65
hrac 2'LEFT'
hrac 3'LEFT'
tah 66
hrac 2'LEFT'
hrac 3'LEFT'
tah 67
hrac 2'UP'
hrac 3'DOWN'
tah 68
hrac 2'UP'
hrac 3'DOWN'
tah 69
hrac 2'DOWN'
hrac 3'DOWN'
tah 70
hrac 2'UP'
hrac 3'LEFT'
tah 71
hrac 2'RIGHT'
hrac 3'LEFT'
tah 72
hrac 2'DOWN'
hrac 3'DOWN'
tah 73
hrac 2'RIGHT'
hrac 3'LEFT'
tah 74
hrac 2'UP'
hrac 3'LEFT'
tah 75
hrac 2'RIGHT'
hrac 3'UP'
tah 76
hrac 2'RIGHT'
hrac 3'LEFT'
tah 77
hrac 2'DOWN'
hrac 3'UP'
tah 78
hrac 2'DOWN'
hrac 3'UP'
tah 79
hrac 2'UP'
hrac 3'UP'
tah 80
hrac 2'UP'
hrac 3'UP'
tah 81
hrac 2'LEFT'
hrac 3'UP'
tah 82
hrac 2'UP'
hrac 3'LEFT'
tah 83
hrac 2'UP'
hrac 3'UP'
tah 84
hrac 2'RIGHT'
hrac 3'LEFT'
tah 85
hrac 2'UP'
hrac 3'DOWN'
tah 86
hrac 2'RIGHT'
hrac 3'DOWN'
tah 87
hrac 2'RIGHT'
hrac 3'UP'
tah 88
hrac 2'RIGHT'
hrac 3'LEFT'
tah 89
hrac 2'RIGHT'
hrac 3'LEFT'
tah 90
hrac 2'DOWN'
hrac 3'DOWN'
tah 91
hrac 2'DOWN'
hrac 3'DOWN'
tah 92
hrac 2'DOWN'
hrac 3'DOWN'
tah 93
hrac 2'DOWN'
hrac 3'LEFT'
tah 94
hrac 2'DOWN'
hrac 3'DOWN'
tah 95
hrac 2'LEFT'
hrac 3'DOWN'
tah 96
hrac 2'DOWN'
hrac 3'DOWN'
tah 97
hrac 2'RIGHT'
hrac 3'RIGHT'
tah 98
hrac 2'RIGHT'
hrac 3'UP'
tah 99
hrac 2'DOWN'
hrac 3'UP'
tah 100
hrac 2'DOWN'
hrac 3 bol zabity hracom 3
proces 28842 umrel na: Terminated
tah 101
hrac 2'LEFT'
tah 102
hrac 2'RIGHT'
tah 103
hrac 2'RIGHT'
tah 104
hrac 2'RIGHT'
tah 105
hrac 2'RIGHT'
tah 106
hrac 2'UP'
tah 107
hrac 2'UP'
tah 108
hrac 2'UP'
ukoncujem klientov
[21:02:18.968] 
