[21:14:07.576] startujem server, seed je 2158315267
main: prepisujem zaznamovy adresar: zaznamy/000005
[21:14:07.576] restartujem klienta paulinia
[21:14:07.576] restartujem klienta m
[21:14:07.576] restartujem klienta okno
[21:14:07.576] restartujem klienta nulano
tah 0
hrac 0'DOWN'
hrac 1'LEFT'
hrac 2'DOWN'
hrac 3'RIGHT'
tah 1
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'DOWN'
hrac 0'DOWN'
tah 2
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 2'DOWN'
hrac 0'RIGHT'
tah 3
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 4
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'UP'
hrac 0'UP'
tah 5
hrac 3'LEFT'
hrac 1'DOWN'
hrac 2'UP'
hrac 0'UP'
tah 6
hrac 3'DOWN'
hrac 1'LEFT'
hrac 2'UP'
hrac 0'UP'
tah 7
hrac 3'LEFT'
hrac 1'LEFT'
hrac 2'DOWN'
hrac 0'UP'
tah 8
hrac 3'DOWN'
hrac 1'UP'
hrac 2'DOWN'
hrac 0'LEFT'
tah 9
hrac 3'UP'
hrac 1'RIGHT'
hrac 2'DOWN'
hrac 0'LEFT'
tah 10
hrac 3'DOWN'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 11
hrac 1'LEFT'
hrac 2'RIGHT'
hrac 3'DOWN'
hrac 0'LEFT'
tah 12
hrac 3'UP'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'DOWN'
tah 13
hrac 1'UP'
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'DOWN'
tah 14
hrac 3'UP'
hrac 2'DOWN'
hrac 1'RIGHT'
hrac 0'DOWN'
tah 15
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 2'DOWN'
hrac 0'DOWN'
tah 16
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 17
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'UP'
tah 18
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'DOWN'
tah 19
hrac 3'LEFT'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'DOWN'
tah 20
hrac 3'UP'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 21
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'UP'
hrac 0'RIGHT'
tah 22
hrac 3'UP'
hrac 1'UP'
hrac 2'UP'
hrac 0'RIGHT'
tah 23
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'UP'
hrac 0'UP'
tah 24
hrac 3'LEFT'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 25
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 26
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 0'UP'
tah 27
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 28
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 0'UP'
tah 29
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 0'UP'
tah 30
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 2'DOWN'
hrac 0'UP'
tah 31
hrac 3'DOWN'
hrac 1'DOWN'
hrac 2'DOWN'
hrac 0'UP'
tah 32
hrac 3'LEFT'
hrac 1'DOWN'
hrac 2'LEFT'
hrac 0'LEFT'
tah 33
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 2'DOWN'
hrac 0'LEFT'
tah 34
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 2'DOWN'
hrac 0'LEFT'
tah 35
hrac 3'LEFT'
hrac 1'DOWN'
hrac 2'DOWN'
hrac 0'LEFT'
tah 36
hrac 3'DOWN'
hrac 1'DOWN'
hrac 2'DOWN'
hrac 0'LEFT'
tah 37
hrac 3'UP'
hrac 1'DOWN'
hrac 2'LEFT'
hrac 0'LEFT'
tah 38
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 2'UP'
hrac 0'DOWN'
tah 39
hrac 3'DOWN'
hrac 1'DOWN'
hrac 2'UP'
hrac 0'DOWN'
tah 40
hrac 3'LEFT'
hrac 1'DOWN'
hrac 2'UP'
hrac 0'DOWN'
tah 41
hrac 3'DOWN'
hrac 1'DOWN'
hrac 2'LEFT'
hrac 0'DOWN'
tah 42
hrac 3'UP'
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 0'DOWN'
tah 43
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 2'DOWN'
hrac 0'RIGHT'
tah 44
hrac 3'DOWN'
hrac 1'DOWN'
hrac 2'LEFT'
hrac 0'DOWN'
tah 45
hrac 3'UP'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'UP'
tah 46
hrac 3'UP'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'LEFT'
tah 47
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'UP'
hrac 0'LEFT'
tah 48
hrac 3'LEFT'
hrac 1'LEFT'
hrac 2'UP'
hrac 0'RIGHT'
tah 49
hrac 3'UP'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'DOWN'
tah 50
hrac 3'DOWN'
hrac 1'LEFT'
hrac 2'UP'
hrac 0'UP'
hrac 3 bol zabity hracom 0
hrac 0 bol zabity hracom 3
proces 29262 umrel na: Terminated
proces 29265 umrel na: Terminated
write: pid -1: Bad file descriptor
write: pid -1: Bad file descriptor
tah 51
hrac 2'UP'
hrac 1'LEFT'
tah 52
hrac 2'DOWN'
hrac 1'LEFT'
tah 53
hrac 2'DOWN'
hrac 1'LEFT'
tah 54
hrac 2'DOWN'
hrac 1'LEFT'
tah 55
hrac 2'DOWN'
hrac 1'RIGHT'
tah 56
hrac 2'DOWN'
hrac 1'DOWN'
tah 57
hrac 2'LEFT'
hrac 1'DOWN'
tah 58
hrac 2'LEFT'
hrac 1'RIGHT'
tah 59
hrac 2'UP'
hrac 1'RIGHT'
tah 60
hrac 2'RIGHT'
hrac 1'UP'
tah 61
hrac 2'RIGHT'
hrac 1'UP'
tah 62
hrac 2'DOWN'
hrac 1'LEFT'
tah 63
hrac 2'DOWN'
hrac 1'DOWN'
tah 64
hrac 2'UP'
hrac 1'DOWN'
tah 65
hrac 2'UP'
hrac 1'DOWN'
tah 66
hrac 2'DOWN'
hrac 1'UP'
tah 67
hrac 2'RIGHT'
hrac 1'LEFT'
tah 68
hrac 2'DOWN'
hrac 1'UP'
tah 69
hrac 2'LEFT'
hrac 1'LEFT'
tah 70
hrac 2'LEFT'
hrac 1'RIGHT'
tah 71
hrac 1'LEFT'
hrac 2'DOWN'
tah 72
hrac 1'DOWN'
hrac 2'DOWN'
tah 73
hrac 2'LEFT'
hrac 1'DOWN'
tah 74
hrac 1'LEFT'
hrac 2'UP'
tah 75
hrac 1'LEFT'
hrac 2'UP'
tah 76
hrac 1'UP'
hrac 2'UP'
tah 77
hrac 1'RIGHT'
hrac 2'UP'
tah 78
hrac 1'UP'
hrac 2'RIGHT'
tah 79
hrac 1'RIGHT'
hrac 2'UP'
tah 80
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 81
hrac 1'DOWN'
hrac 2'UP'
tah 82
hrac 1'DOWN'
hrac 2'UP'
tah 83
hrac 2'UP'
hrac 1'RIGHT'
tah 84
hrac 2'UP'
hrac 1'RIGHT'
tah 85
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 86
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 87
hrac 2'UP'
hrac 1'RIGHT'
tah 88
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 89
hrac 2'UP'
hrac 1'RIGHT'
tah 90
hrac 2'UP'
hrac 1'RIGHT'
tah 91
hrac 2'UP'
hrac 1'RIGHT'
tah 92
hrac 1'UP'
hrac 2'RIGHT'
tah 93
hrac 1'LEFT'
hrac 2'RIGHT'
tah 94
hrac 2'RIGHT'
hrac 1'LEFT'
tah 95
hrac 2'DOWN'
hrac 1'UP'
tah 96
hrac 2'LEFT'
hrac 1'RIGHT'
tah 97
hrac 2'DOWN'
hrac 1'RIGHT'
tah 98
hrac 2'LEFT'
hrac 1'RIGHT'
tah 99
hrac 2'LEFT'
hrac 1'UP'
tah 100
hrac 2'DOWN'
hrac 1'UP'
tah 101
hrac 2'DOWN'
hrac 1'UP'
tah 102
hrac 2'RIGHT'
hrac 1'UP'
tah 103
hrac 2'RIGHT'
hrac 1'LEFT'
tah 104
hrac 2'RIGHT'
hrac 1'DOWN'
tah 105
hrac 2'RIGHT'
hrac 1'DOWN'
tah 106
hrac 2'RIGHT'
hrac 1'DOWN'
tah 107
hrac 2'DOWN'
hrac 1'LEFT'
tah 108
hrac 2'LEFT'
hrac 1'LEFT'
tah 109
hrac 2'LEFT'
hrac 1'LEFT'
tah 110
hrac 2'LEFT'
hrac 1'UP'
tah 111
hrac 2'DOWN'
hrac 1'RIGHT'
tah 112
hrac 2'DOWN'
hrac 1'DOWN'
tah 113
hrac 2'DOWN'
hrac 1'DOWN'
tah 114
hrac 2'RIGHT'
hrac 1'UP'
tah 115
hrac 2'DOWN'
hrac 1'UP'
tah 116
hrac 2'LEFT'
hrac 1'UP'
tah 117
hrac 2'LEFT'
hrac 1'RIGHT'
tah 118
hrac 1'RIGHT'
hrac 2'DOWN'
tah 119
hrac 2'DOWN'
hrac 1'LEFT'
tah 120
hrac 2'DOWN'
hrac 1'UP'
tah 121
hrac 2'DOWN'
hrac 1'LEFT'
tah 122
hrac 2'LEFT'
hrac 1'UP'
tah 123
hrac 2'UP'
hrac 1'RIGHT'
tah 124
hrac 2'UP'
hrac 1'UP'
tah 125
hrac 2'RIGHT'
hrac 1'UP'
tah 126
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 127
hrac 2'DOWN'
hrac 1'RIGHT'
tah 128
hrac 1'UP'
hrac 2'UP'
tah 129
hrac 1'UP'
hrac 2'UP'
tah 130
hrac 1'UP'
hrac 2'RIGHT'
tah 131
hrac 2'DOWN'
hrac 1'UP'
tah 132
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 133
hrac 2'DOWN'
hrac 1'RIGHT'
tah 134
hrac 2'LEFT'
hrac 1'RIGHT'
tah 135
hrac 2'LEFT'
hrac 1'UP'
tah 136
hrac 2'LEFT'
hrac 1'RIGHT'
tah 137
hrac 2'DOWN'
hrac 1'RIGHT'
tah 138
hrac 2'DOWN'
hrac 1'RIGHT'
tah 139
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 140
hrac 2'DOWN'
hrac 1'RIGHT'
tah 141
hrac 2'LEFT'
hrac 1'DOWN'
tah 142
hrac 1'LEFT'
hrac 2'LEFT'
tah 143
hrac 1'LEFT'
hrac 2'UP'
tah 144
hrac 1'LEFT'
hrac 2'UP'
tah 145
hrac 1'LEFT'
hrac 2'UP'
tah 146
hrac 1'DOWN'
hrac 2'DOWN'
tah 147
hrac 1'DOWN'
hrac 2'DOWN'
tah 148
hrac 1'LEFT'
hrac 2'DOWN'
tah 149
hrac 1'LEFT'
hrac 2'DOWN'
tah 150
hrac 1'LEFT'
hrac 2'DOWN'
tah 151
hrac 1'DOWN'
hrac 2'RIGHT'
tah 152
hrac 1'DOWN'
hrac 2'DOWN'
tah 153
hrac 1'DOWN'
hrac 2'LEFT'
tah 154
hrac 1'LEFT'
hrac 2'LEFT'
tah 155
hrac 1'LEFT'
hrac 2'UP'
tah 156
hrac 1'DOWN'
hrac 2'UP'
tah 157
hrac 1'DOWN'
hrac 2'UP'
tah 158
hrac 1'LEFT'
hrac 2'RIGHT'
tah 159
hrac 1'LEFT'
hrac 2'RIGHT'
tah 160
hrac 1'UP'
hrac 2'DOWN'
tah 161
hrac 1'UP'
hrac 2'RIGHT'
tah 162
hrac 1'UP'
hrac 2'DOWN'
tah 163
hrac 1'UP'
hrac 2'DOWN'
tah 164
hrac 1'LEFT'
hrac 2'LEFT'
tah 165
hrac 1'LEFT'
hrac 2'LEFT'
tah 166
hrac 1'DOWN'
hrac 2'DOWN'
tah 167
hrac 1'UP'
hrac 2'DOWN'
tah 168
hrac 1'UP'
hrac 2'DOWN'
tah 169
hrac 1'RIGHT'
hrac 2'LEFT'
tah 170
hrac 1'RIGHT'
hrac 2'UP'
tah 171
hrac 1'RIGHT'
hrac 2'UP'
tah 172
hrac 1'RIGHT'
hrac 2'UP'
tah 173
hrac 1'RIGHT'
hrac 2'UP'
tah 174
hrac 1'LEFT'
hrac 2'DOWN'
tah 175
hrac 1'UP'
hrac 2'DOWN'
tah 176
hrac 1'UP'
hrac 2'DOWN'
tah 177
hrac 1'LEFT'
hrac 2'DOWN'
tah 178
hrac 1'LEFT'
hrac 2'DOWN'
tah 179
hrac 1'LEFT'
hrac 2'RIGHT'
tah 180
hrac 1'UP'
hrac 2'RIGHT'
tah 181
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 182
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 183
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 184
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 185
hrac 2'UP'
hrac 1'RIGHT'
tah 186
hrac 2'LEFT'
hrac 1'RIGHT'
tah 187
hrac 2'LEFT'
hrac 1'DOWN'
tah 188
hrac 2'LEFT'
hrac 1'DOWN'
tah 189
hrac 2'LEFT'
hrac 1'DOWN'
tah 190
hrac 2'LEFT'
hrac 1'DOWN'
tah 191
hrac 2'LEFT'
hrac 1'DOWN'
tah 192
hrac 2'DOWN'
hrac 1'DOWN'
tah 193
hrac 2'LEFT'
hrac 1'LEFT'
tah 194
hrac 2'RIGHT'
hrac 1'LEFT'
tah 195
hrac 2'RIGHT'
hrac 1'DOWN'
tah 196
hrac 2'LEFT'
hrac 1'DOWN'
tah 197
hrac 2'LEFT'
hrac 1'RIGHT'
tah 198
hrac 2'LEFT'
hrac 1'DOWN'
tah 199
hrac 2'RIGHT'
hrac 1'DOWN'
tah 200
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 201
hrac 2'LEFT'
hrac 1'RIGHT'
tah 202
hrac 2'LEFT'
hrac 1'UP'
tah 203
hrac 2'LEFT'
hrac 1'UP'
tah 204
hrac 2'RIGHT'
hrac 1'UP'
tah 205
hrac 2'RIGHT'
hrac 1'UP'
tah 206
hrac 2'LEFT'
hrac 1'UP'
tah 207
hrac 2'LEFT'
hrac 1'LEFT'
tah 208
hrac 2'LEFT'
hrac 1'LEFT'
tah 209
hrac 2'RIGHT'
hrac 1'UP'
tah 210
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 211
hrac 2'LEFT'
hrac 1'RIGHT'
tah 212
hrac 2'LEFT'
hrac 1'UP'
tah 213
hrac 2'LEFT'
hrac 1'RIGHT'
tah 214
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 215
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 216
hrac 2'LEFT'
hrac 1'UP'
tah 217
hrac 2'LEFT'
hrac 1'UP'
tah 218
hrac 2'LEFT'
hrac 1'RIGHT'
tah 219
hrac 2'RIGHT'
hrac 1'DOWN'
tah 220
hrac 2'RIGHT'
hrac 1'DOWN'
tah 221
hrac 2'LEFT'
hrac 1'DOWN'
tah 222
hrac 2'LEFT'
hrac 1'LEFT'
tah 223
hrac 2'LEFT'
hrac 1'UP'
tah 224
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 225
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 226
hrac 2'LEFT'
hrac 1'RIGHT'
tah 227
hrac 2'LEFT'
hrac 1'RIGHT'
tah 228
hrac 2'LEFT'
hrac 1'RIGHT'
tah 229
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 230
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 231
hrac 2'LEFT'
hrac 1'UP'
tah 232
hrac 2'LEFT'
hrac 1'RIGHT'
tah 233
hrac 2'LEFT'
hrac 1'DOWN'
tah 234
hrac 2'RIGHT'
hrac 1'DOWN'
tah 235
hrac 2'RIGHT'
hrac 1'DOWN'
tah 236
hrac 2'UP'
hrac 1'DOWN'
tah 237
hrac 2'RIGHT'
hrac 1'DOWN'
tah 238
hrac 2'RIGHT'
hrac 1'DOWN'
tah 239
hrac 2'RIGHT'
hrac 1'DOWN'
tah 240
hrac 2'RIGHT'
hrac 1'DOWN'
tah 241
hrac 2'RIGHT'
hrac 1'DOWN'
tah 242
hrac 2'RIGHT'
hrac 1'LEFT'
tah 243
hrac 2'RIGHT'
hrac 1'UP'
tah 244
hrac 2'UP'
hrac 1'UP'
tah 245
hrac 2'RIGHT'
hrac 1'UP'
tah 246
hrac 2'UP'
hrac 1'UP'
tah 247
hrac 2'UP'
hrac 1'LEFT'
tah 248
hrac 2'UP'
hrac 1'LEFT'
tah 249
hrac 2'UP'
hrac 1'LEFT'
tah 250
hrac 2'UP'
hrac 1'DOWN'
tah 251
hrac 2'UP'
hrac 1'DOWN'
tah 252
hrac 2'RIGHT'
hrac 1'DOWN'
tah 253
hrac 2'UP'
hrac 1'LEFT'
tah 254
hrac 2'UP'
hrac 1'LEFT'
tah 255
hrac 2'UP'
hrac 1'DOWN'
tah 256
hrac 2'UP'
hrac 1'RIGHT'
tah 257
hrac 2'RIGHT'
hrac 1'DOWN'
tah 258
hrac 2'UP'
hrac 1'LEFT'
tah 259
hrac 2'UP'
hrac 1'LEFT'
tah 260
hrac 2'UP'
hrac 1'LEFT'
tah 261
hrac 2'UP'
hrac 1'LEFT'
tah 262
hrac 1'LEFT'
hrac 2'UP'
tah 263
hrac 1'LEFT'
hrac 2'UP'
tah 264
hrac 1'UP'
hrac 2'UP'
tah 265
hrac 1'UP'
hrac 2'UP'
tah 266
hrac 1'LEFT'
hrac 2'RIGHT'
tah 267
hrac 1'DOWN'
hrac 2'UP'
tah 268
hrac 1'LEFT'
hrac 2'UP'
tah 269
hrac 1'UP'
hrac 2'UP'
tah 270
hrac 1'DOWN'
hrac 2'RIGHT'
tah 271
hrac 1'DOWN'
hrac 2'DOWN'
tah 272
hrac 1'DOWN'
hrac 2'LEFT'
tah 273
hrac 1'DOWN'
hrac 2'LEFT'
tah 274
hrac 1'LEFT'
hrac 2'DOWN'
tah 275
hrac 1'UP'
hrac 2'DOWN'
tah 276
hrac 1'LEFT'
hrac 2'DOWN'
tah 277
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 278
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 279
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 280
hrac 1'RIGHT'
hrac 2'DOWN'
tah 281
hrac 1'DOWN'
hrac 2'DOWN'
tah 282
hrac 1'DOWN'
hrac 2'LEFT'
tah 283
hrac 1'LEFT'
hrac 2'LEFT'
tah 284
hrac 1'DOWN'
hrac 2'DOWN'
tah 285
hrac 1'DOWN'
hrac 2'DOWN'
tah 286
hrac 1'RIGHT'
hrac 2'DOWN'
tah 287
hrac 1'DOWN'
hrac 2'RIGHT'
tah 288
hrac 1'DOWN'
hrac 2'RIGHT'
tah 289
hrac 1'DOWN'
hrac 2'DOWN'
tah 290
hrac 1'RIGHT'
hrac 2'LEFT'
tah 291
hrac 1'RIGHT'
hrac 2'DOWN'
tah 292
hrac 1'UP'
hrac 2'LEFT'
tah 293
hrac 1'UP'
hrac 2'LEFT'
tah 294
hrac 1'UP'
hrac 2'DOWN'
tah 295
hrac 2'DOWN'
hrac 1'RIGHT'
tah 296
hrac 1'RIGHT'
hrac 2'DOWN'
tah 297
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 298
hrac 1'RIGHT'
hrac 2'DOWN'
tah 299
hrac 1'RIGHT'
hrac 2'LEFT'
tah 300
hrac 1'UP'
hrac 2'LEFT'
tah 301
hrac 1'UP'
hrac 2'DOWN'
tah 302
hrac 1'UP'
hrac 2'DOWN'
tah 303
hrac 1'UP'
hrac 2'DOWN'
tah 304
hrac 1'UP'
hrac 2'DOWN'
tah 305
hrac 1'UP'
hrac 2'DOWN'
tah 306
hrac 1'UP'
hrac 2'DOWN'
tah 307
hrac 1'RIGHT'
hrac 2'LEFT'
tah 308
hrac 1'RIGHT'
hrac 2'LEFT'
tah 309
hrac 1'RIGHT'
hrac 2'DOWN'
tah 310
hrac 1'LEFT'
hrac 2'DOWN'
tah 311
hrac 1'DOWN'
hrac 2'RIGHT'
tah 312
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 313
hrac 1'RIGHT'
hrac 2'LEFT'
tah 314
hrac 1'RIGHT'
hrac 2'LEFT'
tah 315
hrac 1'RIGHT'
hrac 2'LEFT'
tah 316
hrac 1'RIGHT'
hrac 2'LEFT'
tah 317
hrac 1'DOWN'
hrac 2'LEFT'
tah 318
hrac 1'RIGHT'
hrac 2'LEFT'
tah 319
hrac 1'DOWN'
hrac 2'LEFT'
tah 320
hrac 1'DOWN'
hrac 2'LEFT'
tah 321
hrac 1'LEFT'
hrac 2'LEFT'
tah 322
hrac 1'UP'
hrac 2'LEFT'
tah 323
hrac 1'LEFT'
hrac 2'LEFT'
tah 324
hrac 1'LEFT'
hrac 2'LEFT'
tah 325
hrac 1'DOWN'
hrac 2'LEFT'
tah 326
hrac 1'DOWN'
hrac 2'LEFT'
tah 327
hrac 1'DOWN'
hrac 2'LEFT'
tah 328
hrac 1'RIGHT'
hrac 2'LEFT'
tah 329
hrac 1'DOWN'
hrac 2'LEFT'
tah 330
hrac 1'RIGHT'
hrac 2'LEFT'
tah 331
hrac 1'RIGHT'
hrac 2'LEFT'
tah 332
hrac 1'DOWN'
hrac 2'LEFT'
tah 333
hrac 1'DOWN'
hrac 2'LEFT'
tah 334
hrac 1'LEFT'
hrac 2'LEFT'
tah 335
hrac 1'LEFT'
hrac 2'LEFT'
tah 336
hrac 1'LEFT'
hrac 2'LEFT'
tah 337
hrac 1'LEFT'
hrac 2'LEFT'
tah 338
hrac 1'DOWN'
hrac 2'LEFT'
tah 339
hrac 1'RIGHT'
hrac 2'LEFT'
tah 340
hrac 1'RIGHT'
hrac 2'UP'
tah 341
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 342
hrac 1'DOWN'
hrac 2'RIGHT'
tah 343
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 344
hrac 1'DOWN'
hrac 2'RIGHT'
tah 345
hrac 1'DOWN'
hrac 2'RIGHT'
tah 346
hrac 1'DOWN'
hrac 2'RIGHT'
tah 347
hrac 1'DOWN'
hrac 2'RIGHT'
tah 348
hrac 1'LEFT'
hrac 2'RIGHT'
tah 349
hrac 1'LEFT'
hrac 2'RIGHT'
tah 350
hrac 1'LEFT'
hrac 2'RIGHT'
tah 351
hrac 1'DOWN'
hrac 2'RIGHT'
tah 352
hrac 1'LEFT'
hrac 2'RIGHT'
tah 353
hrac 1'DOWN'
hrac 2'RIGHT'
tah 354
hrac 1'LEFT'
hrac 2'RIGHT'
tah 355
hrac 1'UP'
hrac 2'RIGHT'
tah 356
hrac 1'UP'
hrac 2'RIGHT'
tah 357
hrac 1'UP'
hrac 2'DOWN'
tah 358
hrac 1'UP'
hrac 2'RIGHT'
tah 359
hrac 1'UP'
hrac 2'RIGHT'
tah 360
hrac 1'UP'
hrac 2'RIGHT'
tah 361
hrac 1'UP'
hrac 2'RIGHT'
tah 362
hrac 1'UP'
hrac 2'RIGHT'
tah 363
hrac 1'UP'
hrac 2'RIGHT'
tah 364
hrac 1'UP'
hrac 2'RIGHT'
tah 365
hrac 1'LEFT'
hrac 2'RIGHT'
tah 366
hrac 1'LEFT'
hrac 2'RIGHT'
tah 367
hrac 1'LEFT'
hrac 2'RIGHT'
tah 368
hrac 1'DOWN'
hrac 2'UP'
tah 369
hrac 1'LEFT'
hrac 2'UP'
tah 370
hrac 1'LEFT'
hrac 2'UP'
tah 371
hrac 1'DOWN'
hrac 2'UP'
tah 372
hrac 1'RIGHT'
hrac 2'UP'
tah 373
hrac 1'RIGHT'
hrac 2'UP'
tah 374
hrac 1'DOWN'
hrac 2'UP'
tah 375
hrac 1'DOWN'
hrac 2'UP'
tah 376
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 377
hrac 1'RIGHT'
hrac 2'UP'
tah 378
hrac 1'RIGHT'
hrac 2'LEFT'
tah 379
hrac 1'LEFT'
hrac 2'LEFT'
tah 380
hrac 1'LEFT'
hrac 2'DOWN'
tah 381
hrac 1'LEFT'
hrac 2'DOWN'
tah 382
hrac 1'LEFT'
hrac 2'DOWN'
tah 383
hrac 1'LEFT'
hrac 2'DOWN'
tah 384
hrac 1'LEFT'
hrac 2'DOWN'
tah 385
hrac 1'LEFT'
hrac 2'DOWN'
tah 386
hrac 1'LEFT'
hrac 2'DOWN'
tah 387
hrac 1'UP'
hrac 2'DOWN'
tah 388
hrac 1'RIGHT'
hrac 2'DOWN'
tah 389
hrac 1'DOWN'
hrac 2'RIGHT'
tah 390
hrac 1'DOWN'
hrac 2'RIGHT'
tah 391
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 392
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 393
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 394
hrac 1'DOWN'
hrac 2'RIGHT'
tah 395
hrac 1'RIGHT'
hrac 2'LEFT'
tah 396
hrac 1'UP'
hrac 2'RIGHT'
tah 397
hrac 1'UP'
hrac 2'UP'
tah 398
hrac 1'RIGHT'
hrac 2'UP'
tah 399
hrac 1'DOWN'
hrac 2'UP'
tah 400
hrac 1'DOWN'
hrac 2'UP'
tah 401
hrac 1'RIGHT'
hrac 2'UP'
tah 402
hrac 1'DOWN'
hrac 2'UP'
tah 403
hrac 1'RIGHT'
hrac 2'UP'
tah 404
hrac 1'DOWN'
hrac 2'UP'
tah 405
hrac 1'DOWN'
hrac 2'LEFT'
tah 406
hrac 1'RIGHT'
hrac 2'LEFT'
tah 407
hrac 1'LEFT'
hrac 2'LEFT'
tah 408
hrac 1'LEFT'
hrac 2'LEFT'
tah 409
hrac 1'RIGHT'
hrac 2'DOWN'
tah 410
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 411
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 412
hrac 1'DOWN'
hrac 2'RIGHT'
tah 413
hrac 1'RIGHT'
hrac 2'DOWN'
tah 414
hrac 1'UP'
hrac 2'LEFT'
tah 415
hrac 1'LEFT'
hrac 2'LEFT'
tah 416
hrac 1'LEFT'
hrac 2'LEFT'
tah 417
hrac 1'LEFT'
hrac 2'LEFT'
tah 418
hrac 1'LEFT'
hrac 2'LEFT'
tah 419
hrac 1'RIGHT'
hrac 2'LEFT'
tah 420
hrac 1'RIGHT'
hrac 2'DOWN'
tah 421
hrac 1'DOWN'
hrac 2'RIGHT'
tah 422
hrac 1'UP'
hrac 2'DOWN'
tah 423
hrac 1'LEFT'
hrac 2'DOWN'
tah 424
hrac 1'UP'
hrac 2'RIGHT'
tah 425
hrac 1'UP'
hrac 2'UP'
tah 426
hrac 1'UP'
hrac 2'UP'
tah 427
hrac 1'UP'
hrac 2'UP'
tah 428
hrac 1'RIGHT'
hrac 2'UP'
tah 429
hrac 1'LEFT'
hrac 2'RIGHT'
tah 430
hrac 1'LEFT'
hrac 2'RIGHT'
tah 431
hrac 1'DOWN'
hrac 2'UP'
tah 432
hrac 1'UP'
hrac 2'UP'
tah 433
hrac 1'DOWN'
hrac 2'RIGHT'
tah 434
hrac 1'LEFT'
hrac 2'RIGHT'
tah 435
hrac 1'DOWN'
hrac 2'RIGHT'
tah 436
hrac 1'RIGHT'
hrac 2'DOWN'
tah 437
hrac 1'RIGHT'
hrac 2'DOWN'
tah 438
hrac 1'LEFT'
hrac 2'DOWN'
tah 439
hrac 1'LEFT'
hrac 2'DOWN'
tah 440
hrac 1'LEFT'
hrac 2'DOWN'
tah 441
hrac 1'LEFT'
hrac 2'DOWN'
tah 442
hrac 1'DOWN'
hrac 2'DOWN'
tah 443
hrac 1'DOWN'
hrac 2'DOWN'
tah 444
hrac 1'LEFT'
hrac 2'DOWN'
tah 445
hrac 1'LEFT'
hrac 2'LEFT'
tah 446
hrac 1'LEFT'
hrac 2'LEFT'
tah 447
hrac 1'LEFT'
hrac 2'RIGHT'
tah 448
hrac 1'LEFT'
hrac 2'RIGHT'
tah 449
hrac 1'LEFT'
hrac 2'UP'
tah 450
hrac 1'LEFT'
hrac 2'UP'
tah 451
hrac 1'UP'
hrac 2'UP'
tah 452
hrac 1'RIGHT'
hrac 2'UP'
tah 453
hrac 1'RIGHT'
hrac 2'UP'
tah 454
hrac 1'UP'
hrac 2'UP'
tah 455
hrac 1'UP'
hrac 2'UP'
tah 456
hrac 1'RIGHT'
hrac 2'UP'
tah 457
hrac 1'RIGHT'
hrac 2'UP'
tah 458
hrac 1'DOWN'
hrac 2'UP'
tah 459
hrac 1'DOWN'
hrac 2'DOWN'
tah 460
hrac 1'RIGHT'
hrac 2'DOWN'
tah 461
hrac 1'RIGHT'
hrac 2'DOWN'
tah 462
hrac 1'UP'
hrac 2'DOWN'
tah 463
hrac 1'UP'
hrac 2'DOWN'
tah 464
hrac 1'UP'
hrac 2'DOWN'
tah 465
hrac 1'LEFT'
hrac 2'DOWN'
tah 466
hrac 1'LEFT'
hrac 2'DOWN'
tah 467
hrac 1'RIGHT'
hrac 2'DOWN'
tah 468
hrac 1'LEFT'
hrac 2'DOWN'
tah 469
hrac 1'LEFT'
hrac 2'LEFT'
tah 470
hrac 1'LEFT'
hrac 2'LEFT'
tah 471
hrac 1'LEFT'
hrac 2'LEFT'
tah 472
hrac 1'LEFT'
hrac 2'LEFT'
tah 473
hrac 1'UP'
hrac 2'LEFT'
tah 474
hrac 1'LEFT'
hrac 2'LEFT'
tah 475
hrac 1'LEFT'
hrac 2'LEFT'
tah 476
hrac 1'UP'
hrac 2'LEFT'
tah 477
hrac 1'LEFT'
hrac 2'LEFT'
tah 478
hrac 1'LEFT'
hrac 2'LEFT'
tah 479
hrac 1'LEFT'
hrac 2'LEFT'
tah 480
hrac 1'LEFT'
hrac 2'LEFT'
tah 481
hrac 1'DOWN'
hrac 2'LEFT'
tah 482
hrac 1'LEFT'
hrac 2'LEFT'
tah 483
hrac 1'UP'
hrac 2'LEFT'
tah 484
hrac 1'UP'
hrac 2'LEFT'
tah 485
hrac 1'LEFT'
hrac 2'LEFT'
tah 486
hrac 1'LEFT'
hrac 2'LEFT'
tah 487
hrac 1'UP'
hrac 2'LEFT'
tah 488
hrac 1'UP'
hrac 2'LEFT'
tah 489
hrac 1'LEFT'
hrac 2'LEFT'
tah 490
hrac 1'LEFT'
hrac 2'LEFT'
tah 491
hrac 1'LEFT'
hrac 2'LEFT'
tah 492
hrac 1'LEFT'
hrac 2'LEFT'
tah 493
hrac 1'UP'
hrac 2'LEFT'
tah 494
hrac 1'UP'
hrac 2'LEFT'
tah 495
hrac 1'UP'
hrac 2'RIGHT'
tah 496
hrac 1'DOWN'
hrac 2'RIGHT'
tah 497
hrac 1'DOWN'
hrac 2'RIGHT'
tah 498
hrac 1'DOWN'
hrac 2'RIGHT'
tah 499
hrac 1'DOWN'
hrac 2'RIGHT'
tah 500
hrac 1'UP'
hrac 2'RIGHT'
tah 501
hrac 1'LEFT'
hrac 2'RIGHT'
tah 502
hrac 1'LEFT'
hrac 2'RIGHT'
tah 503
hrac 1'DOWN'
hrac 2'RIGHT'
tah 504
hrac 1'DOWN'
hrac 2'RIGHT'
tah 505
hrac 1'RIGHT'
hrac 2'LEFT'
tah 506
hrac 1'UP'
hrac 2'LEFT'
tah 507
hrac 1'RIGHT'
hrac 2'LEFT'
tah 508
hrac 1'RIGHT'
hrac 2'LEFT'
tah 509
hrac 1'UP'
hrac 2'LEFT'
tah 510
hrac 1'RIGHT'
hrac 2'LEFT'
tah 511
hrac 1'RIGHT'
hrac 2'LEFT'
tah 512
hrac 1'DOWN'
hrac 2'LEFT'
tah 513
hrac 1'DOWN'
hrac 2'LEFT'
tah 514
hrac 1'RIGHT'
hrac 2'LEFT'
tah 515
hrac 1'DOWN'
hrac 2'RIGHT'
tah 516
hrac 1'DOWN'
hrac 2'RIGHT'
tah 517
hrac 1'DOWN'
hrac 2'RIGHT'
tah 518
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 519
hrac 1'DOWN'
hrac 2'RIGHT'
tah 520
hrac 1'DOWN'
hrac 2'RIGHT'
tah 521
hrac 1'DOWN'
hrac 2'RIGHT'
tah 522
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 523
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 524
hrac 1'UP'
hrac 2'RIGHT'
tah 525
hrac 1'LEFT'
hrac 2'RIGHT'
tah 526
hrac 1'UP'
hrac 2'RIGHT'
tah 527
hrac 1'UP'
hrac 2'RIGHT'
tah 528
hrac 1'UP'
hrac 2'RIGHT'
tah 529
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 530
hrac 1'LEFT'
hrac 2'RIGHT'
tah 531
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 532
hrac 1'DOWN'
hrac 2'RIGHT'
tah 533
hrac 1'DOWN'
hrac 2'RIGHT'
tah 534
hrac 1'LEFT'
hrac 2'RIGHT'
tah 535
hrac 1'DOWN'
hrac 2'RIGHT'
tah 536
hrac 1'LEFT'
hrac 2'RIGHT'
tah 537
hrac 1'LEFT'
hrac 2'RIGHT'
tah 538
hrac 1'DOWN'
hrac 2'RIGHT'
tah 539
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 540
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 541
hrac 1'DOWN'
hrac 2'UP'
tah 542
hrac 1'LEFT'
hrac 2'UP'
tah 543
hrac 1'LEFT'
hrac 2'UP'
tah 544
hrac 1'LEFT'
hrac 2'UP'
tah 545
hrac 1'LEFT'
hrac 2'UP'
tah 546
hrac 1'UP'
hrac 2'UP'
tah 547
hrac 1'UP'
hrac 2'UP'
tah 548
hrac 1'RIGHT'
hrac 2'UP'
tah 549
hrac 1'RIGHT'
hrac 2'UP'
tah 550
hrac 1'UP'
hrac 2'UP'
tah 551
hrac 1'UP'
hrac 2'UP'
tah 552
hrac 1'LEFT'
hrac 2'DOWN'
tah 553
hrac 1'UP'
hrac 2'DOWN'
tah 554
hrac 1'UP'
hrac 2'UP'
tah 555
hrac 1'UP'
hrac 2'UP'
tah 556
hrac 1'LEFT'
hrac 2'UP'
tah 557
hrac 1'RIGHT'
hrac 2'DOWN'
tah 558
hrac 1'LEFT'
hrac 2'DOWN'
tah 559
hrac 1'LEFT'
hrac 2'DOWN'
tah 560
hrac 1'RIGHT'
hrac 2'DOWN'
tah 561
hrac 1'UP'
hrac 2'DOWN'
tah 562
hrac 1'DOWN'
hrac 2'DOWN'
tah 563
hrac 1'DOWN'
hrac 2'DOWN'
tah 564
hrac 1'DOWN'
hrac 2'DOWN'
tah 565
hrac 1'RIGHT'
hrac 2'DOWN'
tah 566
hrac 1'LEFT'
hrac 2'DOWN'
tah 567
hrac 1'LEFT'
hrac 2'DOWN'
tah 568
hrac 1'LEFT'
hrac 2'DOWN'
tah 569
hrac 1'UP'
hrac 2'LEFT'
tah 570
hrac 1'UP'
hrac 2'LEFT'
tah 571
hrac 1'LEFT'
hrac 2'LEFT'
tah 572
hrac 1'DOWN'
hrac 2'LEFT'
tah 573
hrac 1'DOWN'
hrac 2'LEFT'
tah 574
hrac 1'LEFT'
hrac 2'LEFT'
tah 575
hrac 1'UP'
hrac 2'LEFT'
tah 576
hrac 1'UP'
hrac 2'LEFT'
tah 577
hrac 1'DOWN'
hrac 2'LEFT'
tah 578
hrac 1'DOWN'
hrac 2'LEFT'
tah 579
hrac 1'DOWN'
hrac 2'RIGHT'
tah 580
hrac 1'UP'
hrac 2'RIGHT'
tah 581
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 582
hrac 1'DOWN'
hrac 2'RIGHT'
tah 583
hrac 1'DOWN'
hrac 2'RIGHT'
tah 584
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 585
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 586
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 587
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 588
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 589
hrac 1'UP'
hrac 2'UP'
tah 590
hrac 1'RIGHT'
hrac 2'UP'
tah 591
hrac 1'RIGHT'
hrac 2'DOWN'
tah 592
hrac 1'RIGHT'
hrac 2'DOWN'
tah 593
hrac 1'RIGHT'
hrac 2'LEFT'
tah 594
hrac 1'UP'
hrac 2'LEFT'
tah 595
hrac 1'UP'
hrac 2'LEFT'
tah 596
hrac 1'UP'
hrac 2'LEFT'
tah 597
hrac 1'RIGHT'
hrac 2'LEFT'
tah 598
hrac 1'DOWN'
hrac 2'LEFT'
tah 599
hrac 1'DOWN'
hrac 2'LEFT'
tah 600
hrac 1'DOWN'
hrac 2'LEFT'
tah 601
hrac 1'DOWN'
hrac 2'LEFT'
tah 602
hrac 1'RIGHT'
hrac 2'LEFT'
tah 603
hrac 1'RIGHT'
hrac 2'LEFT'
tah 604
hrac 1'RIGHT'
hrac 2'LEFT'
tah 605
hrac 1'UP'
hrac 2'LEFT'
tah 606
hrac 1'UP'
hrac 2'LEFT'
tah 607
hrac 1'RIGHT'
hrac 2'LEFT'
tah 608
hrac 1'DOWN'
hrac 2'LEFT'
tah 609
hrac 1'DOWN'
hrac 2'LEFT'
tah 610
hrac 2'LEFT'
hrac 1'LEFT'
tah 611
hrac 1'DOWN'
hrac 2'LEFT'
tah 612
hrac 1'DOWN'
hrac 2'LEFT'
tah 613
hrac 1'DOWN'
hrac 2'LEFT'
tah 614
hrac 1'RIGHT'
hrac 2'LEFT'
tah 615
hrac 2'LEFT'
hrac 1'DOWN'
tah 616
hrac 2'LEFT'
hrac 1'UP'
tah 617
hrac 2'LEFT'
hrac 1'LEFT'
tah 618
hrac 2'LEFT'
hrac 1'LEFT'
tah 619
hrac 2'LEFT'
hrac 1'UP'
tah 620
hrac 2'LEFT'
hrac 1'RIGHT'
tah 621
hrac 2'LEFT'
hrac 1'LEFT'
tah 622
hrac 2'LEFT'
hrac 1'LEFT'
tah 623
hrac 2'LEFT'
hrac 1'LEFT'
tah 624
hrac 2'UP'
hrac 1'LEFT'
tah 625
hrac 2'UP'
hrac 1'LEFT'
tah 626
hrac 2'RIGHT'
hrac 1'LEFT'
tah 627
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 628
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 629
hrac 1'DOWN'
hrac 2'RIGHT'
tah 630
hrac 1'UP'
hrac 2'RIGHT'
tah 631
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 632
hrac 1'UP'
hrac 2'RIGHT'
tah 633
hrac 1'DOWN'
hrac 2'RIGHT'
tah 634
hrac 1'DOWN'
hrac 2'RIGHT'
tah 635
hrac 1'LEFT'
hrac 2'RIGHT'
tah 636
hrac 1'LEFT'
hrac 2'RIGHT'
tah 637
hrac 1'LEFT'
hrac 2'RIGHT'
tah 638
hrac 1'DOWN'
hrac 2'RIGHT'
tah 639
hrac 1'DOWN'
hrac 2'RIGHT'
tah 640
hrac 1'DOWN'
hrac 2'RIGHT'
hrac 2 bol zabity hracom 1
proces 29264 umrel na: Terminated
write: pid -1: Bad file descriptor
tah 641
hrac 1'DOWN'
tah 642
hrac 1'DOWN'
tah 643
hrac 1'LEFT'
tah 644
hrac 1'LEFT'
tah 645
hrac 1'LEFT'
tah 646
hrac 1'LEFT'
tah 647
hrac 1'LEFT'
tah 648
hrac 1'LEFT'
ukoncujem klientov
[21:14:54.027] 
proces 29263 umrel na: Terminated
