[21:18:56.034] startujem server, seed je 3021884096
main: prepisujem zaznamovy adresar: zaznamy/000009
[21:18:56.034] restartujem klienta paulinia
[21:18:56.034] restartujem klienta m
[21:18:56.035] restartujem klienta okno
[21:18:56.035] restartujem klienta nulano
tah 0
hrac 0'RIGHT'
hrac 1'LEFT'
hrac 2'UP'
hrac 3'UP'
tah 1
hrac 1'LEFT'
hrac 2'UP'
hrac 3'UP'
hrac 0'RIGHT'
tah 2
hrac 1'UP'
hrac 2'RIGHT'
hrac 3'DOWN'
hrac 0'UP'
tah 3
hrac 3'UP'
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 0'UP'
tah 4
hrac 3'LEFT'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 5
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'UP'
hrac 0'LEFT'
tah 6
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'LEFT'
tah 7
hrac 3'DOWN'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'LEFT'
tah 8
hrac 1'LEFT'
hrac 2'LEFT'
hrac 3'RIGHT'
hrac 0'DOWN'
tah 9
hrac 1'DOWN'
hrac 2'LEFT'
hrac 3'LEFT'
hrac 0'DOWN'
tah 10
hrac 1'DOWN'
hrac 2'DOWN'
hrac 3'DOWN'
hrac 0'DOWN'
tah 11
hrac 1'DOWN'
hrac 2'DOWN'
hrac 3'RIGHT'
hrac 0'DOWN'
tah 12
hrac 1'DOWN'
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'RIGHT'
tah 13
hrac 1'LEFT'
hrac 2'DOWN'
hrac 3'RIGHT'
hrac 0'RIGHT'
tah 14
hrac 1'UP'
hrac 2'DOWN'
hrac 3'DOWN'
hrac 0'RIGHT'
tah 15
hrac 1'UP'
hrac 2'LEFT'
hrac 3'LEFT'
hrac 0'RIGHT'
tah 16
hrac 3'DOWN'
hrac 2'LEFT'
hrac 1'UP'
hrac 0'UP'
tah 17
hrac 3'UP'
hrac 2'DOWN'
hrac 1'UP'
hrac 0'LEFT'
tah 18
hrac 3'DOWN'
hrac 2'RIGHT'
hrac 1'UP'
hrac 0'RIGHT'
tah 19
hrac 3'DOWN'
hrac 2'RIGHT'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 20
hrac 3'UP'
hrac 2'RIGHT'
hrac 1'RIGHT'
hrac 0'UP'
tah 21
hrac 3'RIGHT'
hrac 2'UP'
hrac 1'RIGHT'
hrac 0'UP'
tah 22
hrac 3'UP'
hrac 2'UP'
hrac 1'RIGHT'
hrac 0'UP'
tah 23
hrac 3'RIGHT'
hrac 2'UP'
hrac 1'DOWN'
hrac 0'UP'
tah 24
hrac 3'LEFT'
hrac 2'DOWN'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 25
hrac 3'RIGHT'
hrac 2'DOWN'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 26
hrac 3'UP'
hrac 2'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 27
hrac 3'DOWN'
hrac 2'RIGHT'
hrac 1'DOWN'
hrac 0'LEFT'
tah 28
hrac 3'DOWN'
hrac 2'DOWN'
hrac 1'DOWN'
hrac 0'LEFT'
tah 29
hrac 3'UP'
hrac 2'LEFT'
hrac 1'LEFT'
hrac 0'LEFT'
tah 30
hrac 3'RIGHT'
hrac 2'DOWN'
hrac 1'DOWN'
hrac 0'DOWN'
tah 31
hrac 3'LEFT'
hrac 2'RIGHT'
hrac 1'DOWN'
hrac 0'DOWN'
tah 32
hrac 3'DOWN'
hrac 2'RIGHT'
hrac 1'DOWN'
hrac 0'DOWN'
tah 33
hrac 3'RIGHT'
hrac 2'UP'
hrac 1'DOWN'
hrac 0'DOWN'
tah 34
hrac 3'UP'
hrac 2'UP'
hrac 1'LEFT'
hrac 0'DOWN'
tah 35
hrac 3'RIGHT'
hrac 2'UP'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 36
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'LEFT'
tah 37
hrac 1'LEFT'
hrac 2'LEFT'
hrac 3'UP'
hrac 0'LEFT'
tah 38
hrac 3'DOWN'
hrac 2'LEFT'
hrac 1'LEFT'
hrac 0'UP'
tah 39
hrac 3'UP'
hrac 2'UP'
hrac 1'LEFT'
hrac 0'UP'
tah 40
hrac 3'RIGHT'
hrac 2'UP'
hrac 1'DOWN'
hrac 0'UP'
tah 41
hrac 3'DOWN'
hrac 2'UP'
hrac 1'DOWN'
hrac 0'UP'
tah 42
hrac 3'DOWN'
hrac 2'UP'
hrac 1'DOWN'
hrac 0'UP'
tah 43
hrac 3'UP'
hrac 2'LEFT'
hrac 1'DOWN'
hrac 0'UP'
tah 44
hrac 3'RIGHT'
hrac 2'LEFT'
hrac 1'DOWN'
hrac 0'RIGHT'
tah 45
hrac 3'LEFT'
hrac 2'LEFT'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 46
hrac 3'RIGHT'
hrac 2'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
tah 47
hrac 3'RIGHT'
hrac 2'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
tah 48
hrac 3'LEFT'
hrac 2'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
tah 49
hrac 3'UP'
hrac 2'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
tah 50
hrac 3'DOWN'
hrac 2'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
tah 51
hrac 3'RIGHT'
hrac 2'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
tah 52
hrac 3'DOWN'
hrac 2'LEFT'
hrac 1'RIGHT'
hrac 0'DOWN'
tah 53
hrac 3'UP'
hrac 2'LEFT'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 54
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 0'UP'
tah 55
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 3'LEFT'
hrac 0'UP'
tah 56
hrac 3'UP'
hrac 2'DOWN'
hrac 1'DOWN'
hrac 0'LEFT'
tah 57
hrac 3'LEFT'
hrac 2'RIGHT'
hrac 1'DOWN'
hrac 0'LEFT'
tah 58
hrac 3'UP'
hrac 2'RIGHT'
hrac 1'DOWN'
hrac 0'LEFT'
tah 59
hrac 3'DOWN'
hrac 2'RIGHT'
hrac 1'LEFT'
hrac 0'LEFT'
tah 60
hrac 3'RIGHT'
hrac 2'RIGHT'
hrac 1'LEFT'
hrac 0'LEFT'
tah 61
hrac 3'RIGHT'
hrac 2'RIGHT'
hrac 1'LEFT'
hrac 0'LEFT'
tah 62
hrac 3'DOWN'
hrac 2'RIGHT'
hrac 1'LEFT'
hrac 0'LEFT'
tah 63
hrac 3'DOWN'
hrac 2'RIGHT'
hrac 1'UP'
hrac 0'UP'
tah 64
hrac 3'LEFT'
hrac 2'RIGHT'
hrac 1'LEFT'
hrac 0'UP'
tah 65
hrac 3'DOWN'
hrac 2'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 66
hrac 3'UP'
hrac 2'RIGHT'
hrac 1'LEFT'
hrac 0'DOWN'
tah 67
hrac 3'DOWN'
hrac 2'RIGHT'
hrac 1'LEFT'
hrac 0'DOWN'
tah 68
hrac 3'RIGHT'
hrac 2'RIGHT'
hrac 1'DOWN'
hrac 0'DOWN'
tah 69
hrac 3'LEFT'
hrac 2'RIGHT'
hrac 1'LEFT'
hrac 0'DOWN'
tah 70
hrac 3'DOWN'
hrac 2'DOWN'
hrac 1'UP'
hrac 0'DOWN'
tah 71
hrac 3'UP'
hrac 2'DOWN'
hrac 1'UP'
hrac 0'DOWN'
tah 72
hrac 3'DOWN'
hrac 2'DOWN'
hrac 1'RIGHT'
hrac 0'DOWN'
tah 73
hrac 3'RIGHT'
hrac 2'DOWN'
hrac 1'RIGHT'
hrac 0'DOWN'
tah 74
hrac 3'LEFT'
hrac 2'DOWN'
hrac 1'DOWN'
hrac 0'DOWN'
tah 75
hrac 3'RIGHT'
hrac 2'DOWN'
hrac 1'UP'
hrac 0'LEFT'
tah 76
hrac 3'RIGHT'
hrac 2'DOWN'
hrac 1'RIGHT'
hrac 0'UP'
tah 77
hrac 3'LEFT'
hrac 2'DOWN'
hrac 1'LEFT'
hrac 0'UP'
tah 78
hrac 3'RIGHT'
hrac 2'LEFT'
hrac 1'UP'
hrac 0'UP'
tah 79
hrac 3'RIGHT'
hrac 2'UP'
hrac 1'DOWN'
hrac 0'UP'
tah 80
hrac 3'LEFT'
hrac 2'UP'
hrac 1'DOWN'
hrac 0'UP'
tah 81
hrac 3'UP'
hrac 2'UP'
hrac 1'LEFT'
hrac 0'UP'
tah 82
hrac 3'DOWN'
hrac 2'UP'
hrac 1'LEFT'
hrac 0'UP'
tah 83
hrac 3'UP'
hrac 2'UP'
hrac 1'UP'
hrac 0'UP'
tah 84
hrac 3'RIGHT'
hrac 2'LEFT'
hrac 1'LEFT'
hrac 0'UP'
tah 85
hrac 3'DOWN'
hrac 2'UP'
hrac 1'DOWN'
hrac 0'UP'
tah 86
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 3'DOWN'
hrac 0'UP'
tah 87
hrac 1'DOWN'
hrac 2'UP'
hrac 3'UP'
hrac 0'UP'
tah 88
hrac 1'UP'
hrac 2'UP'
hrac 3'RIGHT'
hrac 0'UP'
tah 89
hrac 3'LEFT'
hrac 1'UP'
hrac 0'UP'
hrac 2'UP'
tah 90
hrac 3'RIGHT'
hrac 2'DOWN'
hrac 1'UP'
hrac 0'RIGHT'
tah 91
hrac 1'RIGHT'
hrac 2'DOWN'
hrac 3'UP'
hrac 0'UP'
tah 92
hrac 1'UP'
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'UP'
tah 93
hrac 1'UP'
hrac 2'DOWN'
hrac 3'UP'
hrac 0'UP'
tah 94
hrac 2'DOWN'
hrac 1'LEFT'
hrac 3'DOWN'
hrac 0'UP'
tah 95
hrac 2'DOWN'
hrac 1'LEFT'
hrac 3'LEFT'
hrac 0'UP'
tah 96
hrac 2'DOWN'
hrac 1'UP'
hrac 3'UP'
hrac 0'UP'
tah 97
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 98
hrac 1'DOWN'
hrac 2'LEFT'
hrac 3'RIGHT'
hrac 0'UP'
tah 99
hrac 3'DOWN'
hrac 2'DOWN'
hrac 1'DOWN'
hrac 0'DOWN'
tah 100
hrac 3'RIGHT'
hrac 2'RIGHT'
hrac 1'RIGHT'
hrac 0'UP'
tah 101
hrac 3'LEFT'
hrac 2'RIGHT'
hrac 1'DOWN'
hrac 0'RIGHT'
tah 102
hrac 3'RIGHT'
hrac 2'RIGHT'
hrac 1'DOWN'
hrac 0'LEFT'
tah 103
hrac 3'DOWN'
hrac 2'RIGHT'
hrac 1'LEFT'
hrac 0'UP'
tah 104
hrac 3'LEFT'
hrac 2'RIGHT'
hrac 1'DOWN'
hrac 0'RIGHT'
tah 105
hrac 3'DOWN'
hrac 2'LEFT'
hrac 1'DOWN'
hrac 0'RIGHT'
tah 106
hrac 3'LEFT'
hrac 2'DOWN'
hrac 1'RIGHT'
hrac 0'DOWN'
tah 107
hrac 3'DOWN'
hrac 2'DOWN'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 108
hrac 3'UP'
hrac 2'LEFT'
hrac 1'DOWN'
hrac 0'RIGHT'
tah 109
hrac 3'DOWN'
hrac 2'UP'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 110
hrac 3'RIGHT'
hrac 2'RIGHT'
hrac 1'UP'
hrac 0'RIGHT'
tah 111
hrac 3'LEFT'
hrac 2'RIGHT'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 112
hrac 3'DOWN'
hrac 2'DOWN'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 113
hrac 3'UP'
hrac 2'UP'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 114
hrac 3'LEFT'
hrac 2'UP'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 0 bol zabity hracom 2
proces 29765 umrel na: Terminated
write: pid -1: Bad file descriptor
tah 115
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 2'RIGHT'
tah 116
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 3'RIGHT'
tah 117
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 3'RIGHT'
tah 118
hrac 3'LEFT'
hrac 1'UP'
hrac 2'UP'
tah 119
hrac 1'RIGHT'
hrac 2'UP'
hrac 3'DOWN'
tah 120
hrac 3'LEFT'
hrac 2'RIGHT'
hrac 1'DOWN'
tah 121
hrac 3'DOWN'
hrac 2'DOWN'
hrac 1'LEFT'
tah 122
hrac 3'UP'
hrac 2'LEFT'
hrac 1'LEFT'
tah 123
hrac 3'LEFT'
hrac 2'LEFT'
hrac 1'LEFT'
tah 124
hrac 3'RIGHT'
hrac 2'DOWN'
hrac 1'LEFT'
tah 125
hrac 3'RIGHT'
hrac 2'LEFT'
hrac 1'DOWN'
tah 126
hrac 3'RIGHT'
hrac 2'LEFT'
hrac 1'RIGHT'
tah 127
hrac 3'LEFT'
hrac 2'DOWN'
hrac 1'UP'
tah 128
hrac 3'DOWN'
hrac 2'DOWN'
hrac 1'LEFT'
tah 129
hrac 3'LEFT'
hrac 2'DOWN'
hrac 1'LEFT'
tah 130
hrac 3'DOWN'
hrac 2'RIGHT'
hrac 1'UP'
tah 131
hrac 3'UP'
hrac 2'RIGHT'
hrac 1'UP'
tah 132
hrac 3'LEFT'
hrac 2'UP'
hrac 1'UP'
tah 133
hrac 3'RIGHT'
hrac 2'LEFT'
hrac 1'UP'
tah 134
hrac 3'DOWN'
hrac 2'LEFT'
hrac 1'UP'
tah 135
hrac 3'LEFT'
hrac 2'LEFT'
hrac 1'UP'
tah 136
hrac 3'UP'
hrac 2'DOWN'
hrac 1'RIGHT'
tah 137
hrac 3'LEFT'
hrac 2'DOWN'
hrac 1'RIGHT'
tah 138
hrac 3'RIGHT'
hrac 2'RIGHT'
hrac 1'RIGHT'
tah 139
hrac 3'UP'
hrac 2'RIGHT'
hrac 1'LEFT'
tah 140
hrac 3'LEFT'
hrac 2'UP'
hrac 1'UP'
hrac 2 bol zabity hracom 1
proces 29767 umrel na: Terminated
write: pid -1: Bad file descriptor
tah 141
hrac 3'RIGHT'
hrac 1'LEFT'
tah 142
hrac 3'LEFT'
hrac 1'LEFT'
tah 143
hrac 3'UP'
hrac 1'LEFT'
tah 144
hrac 3'RIGHT'
hrac 1'LEFT'
tah 145
hrac 3'LEFT'
hrac 1'DOWN'
tah 146
hrac 3'LEFT'
hrac 1'LEFT'
tah 147
hrac 3'RIGHT'
hrac 1'LEFT'
tah 148
hrac 3'DOWN'
hrac 1'DOWN'
tah 149
hrac 3'LEFT'
hrac 1'DOWN'
tah 150
hrac 3'RIGHT'
hrac 1'DOWN'
tah 151
hrac 3'LEFT'
hrac 1'DOWN'
tah 152
hrac 3'DOWN'
hrac 1'RIGHT'
tah 153
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 154
hrac 3'DOWN'
hrac 1'RIGHT'
tah 155
hrac 3'UP'
hrac 1'RIGHT'
tah 156
hrac 3'DOWN'
hrac 1'RIGHT'
tah 157
hrac 3'LEFT'
hrac 1'LEFT'
tah 158
hrac 3'UP'
hrac 1'LEFT'
tah 159
hrac 3'LEFT'
hrac 1'DOWN'
tah 160
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 161
hrac 3'UP'
hrac 1'LEFT'
tah 162
hrac 3'LEFT'
hrac 1'LEFT'
tah 163
hrac 3'RIGHT'
hrac 1'LEFT'
tah 164
hrac 3'UP'
hrac 1'LEFT'
tah 165
hrac 3'LEFT'
hrac 1'UP'
tah 166
hrac 3'UP'
hrac 1'UP'
tah 167
hrac 1'LEFT'
hrac 3'LEFT'
tah 168
hrac 3'RIGHT'
hrac 1'UP'
tah 169
hrac 3'DOWN'
hrac 1'RIGHT'
tah 170
hrac 3'LEFT'
hrac 1'LEFT'
tah 171
hrac 3'RIGHT'
hrac 1'LEFT'
tah 172
hrac 3'DOWN'
hrac 1'LEFT'
tah 173
hrac 3'LEFT'
hrac 1'LEFT'
tah 174
hrac 3'UP'
hrac 1'LEFT'
tah 175
hrac 3'LEFT'
hrac 1'DOWN'
tah 176
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 177
hrac 3'DOWN'
hrac 1'RIGHT'
tah 178
hrac 3'DOWN'
hrac 1'RIGHT'
tah 179
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 180
hrac 3'DOWN'
hrac 1'LEFT'
tah 181
hrac 3'RIGHT'
hrac 1'UP'
tah 182
hrac 3'DOWN'
hrac 1'UP'
tah 183
hrac 3'UP'
hrac 1'RIGHT'
tah 184
hrac 3'DOWN'
hrac 1'RIGHT'
tah 185
hrac 3'LEFT'
hrac 1'UP'
tah 186
hrac 3'RIGHT'
hrac 1'LEFT'
tah 187
hrac 3'RIGHT'
hrac 1'LEFT'
tah 188
hrac 3'LEFT'
hrac 1'LEFT'
tah 189
hrac 3'DOWN'
hrac 1'UP'
tah 190
hrac 3'UP'
hrac 1'LEFT'
tah 191
hrac 3'DOWN'
hrac 1'DOWN'
tah 192
hrac 3'DOWN'
hrac 1'DOWN'
tah 193
hrac 3'UP'
hrac 1'DOWN'
tah 194
hrac 3'LEFT'
hrac 1'LEFT'
tah 195
hrac 3'RIGHT'
hrac 1'LEFT'
tah 196
hrac 3'RIGHT'
hrac 1'LEFT'
tah 197
hrac 3'UP'
hrac 1'LEFT'
tah 198
hrac 3'RIGHT'
hrac 1'LEFT'
tah 199
hrac 3'UP'
hrac 1'DOWN'
tah 200
hrac 3'DOWN'
hrac 1'DOWN'
tah 201
hrac 3'RIGHT'
hrac 1'LEFT'
tah 202
hrac 3'LEFT'
hrac 1'UP'
tah 203
hrac 3'DOWN'
hrac 1'UP'
tah 204
hrac 3'UP'
hrac 1'UP'
tah 205
hrac 3'DOWN'
hrac 1'UP'
tah 206
hrac 3'DOWN'
hrac 1'UP'
tah 207
hrac 3'UP'
hrac 1'UP'
tah 208
hrac 3'RIGHT'
hrac 1'UP'
tah 209
hrac 3'UP'
hrac 1'UP'
tah 210
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 211
hrac 3'LEFT'
hrac 1'RIGHT'
tah 212
hrac 3'DOWN'
hrac 1'RIGHT'
tah 213
hrac 3'RIGHT'
hrac 1'UP'
tah 214
hrac 3'UP'
hrac 1'UP'
tah 215
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 216
hrac 3'LEFT'
hrac 1'RIGHT'
tah 217
hrac 3'UP'
hrac 1'RIGHT'
tah 218
hrac 3'LEFT'
hrac 1'DOWN'
tah 219
hrac 3'RIGHT'
hrac 1'DOWN'
tah 220
hrac 3'RIGHT'
hrac 1'DOWN'
tah 221
hrac 3'DOWN'
hrac 1'DOWN'
tah 222
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 223
hrac 3'LEFT'
hrac 1'RIGHT'
tah 224
hrac 3'DOWN'
hrac 1'DOWN'
tah 225
hrac 3'LEFT'
hrac 1'LEFT'
tah 226
hrac 3'DOWN'
hrac 1'UP'
tah 227
hrac 3'UP'
hrac 1'LEFT'
tah 228
hrac 3'LEFT'
hrac 1'UP'
tah 229
hrac 3'DOWN'
hrac 1'RIGHT'
tah 230
hrac 3'UP'
hrac 1'RIGHT'
tah 231
hrac 3'DOWN'
hrac 1'UP'
tah 232
hrac 3'DOWN'
hrac 1'RIGHT'
tah 233
hrac 3'UP'
hrac 1'UP'
tah 234
hrac 3'RIGHT'
hrac 1'UP'
tah 235
hrac 3'RIGHT'
hrac 1'UP'
tah 236
hrac 3'LEFT'
hrac 1'UP'
tah 237
hrac 3'DOWN'
hrac 1'RIGHT'
tah 238
hrac 3'LEFT'
hrac 1'RIGHT'
tah 239
hrac 3'DOWN'
hrac 1'RIGHT'
tah 240
hrac 3'UP'
hrac 1'DOWN'
tah 241
hrac 3'LEFT'
hrac 1'DOWN'
tah 242
hrac 3'UP'
hrac 1'LEFT'
tah 243
hrac 3'LEFT'
hrac 1'LEFT'
tah 244
hrac 3'RIGHT'
hrac 1'DOWN'
tah 245
hrac 3'DOWN'
hrac 1'RIGHT'
tah 246
hrac 3'LEFT'
hrac 1'RIGHT'
tah 247
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 248
hrac 3'DOWN'
hrac 1'RIGHT'
tah 249
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 250
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 251
hrac 3'UP'
hrac 1'RIGHT'
tah 252
hrac 3'RIGHT'
hrac 1'UP'
tah 253
hrac 3'UP'
hrac 1'UP'
tah 254
hrac 3'RIGHT'
hrac 1'UP'
tah 255
hrac 3'LEFT'
hrac 1'UP'
tah 256
hrac 3'UP'
hrac 1'UP'
tah 257
hrac 3'RIGHT'
hrac 1'UP'
tah 258
hrac 3'UP'
hrac 1'RIGHT'
tah 259
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 260
hrac 3'LEFT'
hrac 1'RIGHT'
tah 261
hrac 3'UP'
hrac 1'RIGHT'
tah 262
hrac 3'DOWN'
hrac 1'RIGHT'
tah 263
hrac 3'DOWN'
hrac 1'RIGHT'
tah 264
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 265
hrac 3'LEFT'
hrac 1'RIGHT'
tah 266
hrac 3'DOWN'
hrac 1'UP'
tah 267
hrac 3'DOWN'
hrac 1'UP'
tah 268
hrac 3'UP'
hrac 1'RIGHT'
tah 269
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 270
hrac 3'UP'
hrac 1'RIGHT'
tah 271
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 272
hrac 3'LEFT'
hrac 1'DOWN'
tah 273
hrac 3'UP'
hrac 1'LEFT'
tah 274
hrac 3'UP'
hrac 1'LEFT'
tah 275
hrac 3'DOWN'
hrac 1'LEFT'
tah 276
hrac 3'RIGHT'
hrac 1'DOWN'
tah 277
hrac 3'LEFT'
hrac 1'DOWN'
tah 278
hrac 3'RIGHT'
hrac 1'DOWN'
tah 279
hrac 3'UP'
hrac 1'DOWN'
tah 280
hrac 3'DOWN'
hrac 1'DOWN'
tah 281
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 282
hrac 3'LEFT'
hrac 1'DOWN'
tah 283
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 284
hrac 3'UP'
hrac 1'UP'
tah 285
hrac 3'LEFT'
hrac 1'RIGHT'
tah 286
hrac 3'UP'
hrac 1'DOWN'
tah 287
hrac 3'DOWN'
hrac 1'DOWN'
tah 288
hrac 3'UP'
hrac 1'DOWN'
tah 289
hrac 3'RIGHT'
hrac 1'DOWN'
tah 290
hrac 3'DOWN'
hrac 1'DOWN'
tah 291
hrac 3'RIGHT'
hrac 1'LEFT'
tah 292
hrac 3'LEFT'
hrac 1'RIGHT'
tah 293
hrac 3'RIGHT'
hrac 1'UP'
tah 294
hrac 3'DOWN'
hrac 1'DOWN'
tah 295
hrac 3'UP'
hrac 1'DOWN'
tah 296
hrac 3'UP'
hrac 1'DOWN'
tah 297
hrac 1'DOWN'
hrac 3'DOWN'
tah 298
hrac 3'RIGHT'
hrac 1'LEFT'
tah 299
hrac 3'LEFT'
hrac 1'RIGHT'
tah 300
hrac 3'RIGHT'
hrac 1'DOWN'
tah 301
hrac 3'RIGHT'
hrac 1'DOWN'
tah 302
hrac 3'LEFT'
hrac 1'DOWN'
tah 303
hrac 3'UP'
hrac 1'DOWN'
tah 304
hrac 3'DOWN'
hrac 1'DOWN'
tah 305
hrac 3'DOWN'
hrac 1'DOWN'
tah 306
hrac 3'UP'
hrac 1'DOWN'
tah 307
hrac 3'UP'
hrac 1'DOWN'
tah 308
hrac 3'RIGHT'
hrac 1'LEFT'
tah 309
hrac 3'LEFT'
hrac 1'UP'
tah 310
hrac 3'UP'
hrac 1'UP'
tah 311
hrac 3'UP'
hrac 1'UP'
tah 312
hrac 3'LEFT'
hrac 1'LEFT'
tah 313
hrac 3'RIGHT'
hrac 1'LEFT'
tah 314
hrac 3'RIGHT'
hrac 1'UP'
tah 315
hrac 3'LEFT'
hrac 1'UP'
tah 316
hrac 3'UP'
hrac 1'LEFT'
tah 317
hrac 3'LEFT'
hrac 1'DOWN'
tah 318
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 319
hrac 3'RIGHT'
hrac 1'LEFT'
tah 320
hrac 3'DOWN'
hrac 1'LEFT'
tah 321
hrac 3'RIGHT'
hrac 1'DOWN'
tah 322
hrac 3'LEFT'
hrac 1'RIGHT'
tah 323
hrac 3'UP'
hrac 1'RIGHT'
tah 324
hrac 3'RIGHT'
hrac 1'DOWN'
tah 325
hrac 3'DOWN'
hrac 1'RIGHT'
tah 326
hrac 3'RIGHT'
hrac 1'DOWN'
tah 327
hrac 3'LEFT'
hrac 1'DOWN'
tah 328
hrac 3'DOWN'
hrac 1'DOWN'
tah 329
hrac 3'UP'
hrac 1'RIGHT'
tah 330
hrac 3'RIGHT'
hrac 1'UP'
tah 331
hrac 3'RIGHT'
hrac 1'LEFT'
tah 332
hrac 3'LEFT'
hrac 1'DOWN'
tah 333
hrac 3'UP'
hrac 1'LEFT'
tah 334
hrac 3'DOWN'
hrac 1'UP'
tah 335
hrac 3'DOWN'
hrac 1'RIGHT'
tah 336
hrac 3'LEFT'
hrac 1'DOWN'
tah 337
hrac 3'DOWN'
hrac 1'RIGHT'
tah 338
hrac 3'LEFT'
hrac 1'DOWN'
tah 339
hrac 3'RIGHT'
hrac 1'LEFT'
tah 340
hrac 3'RIGHT'
hrac 1'LEFT'
tah 341
hrac 3'UP'
hrac 1'UP'
tah 342
hrac 3'RIGHT'
hrac 1'RIGHT'
tah 343
hrac 3'LEFT'
hrac 1'LEFT'
tah 344
hrac 3'RIGHT'
hrac 1'DOWN'
tah 345
hrac 3'DOWN'
hrac 1'DOWN'
tah 346
hrac 3'UP'
hrac 1'UP'
tah 347
hrac 3'RIGHT'
hrac 1'UP'
tah 348
hrac 3'LEFT'
hrac 1'UP'
hrac 3 bol zabity hracom 1
proces 29768 umrel na: Terminated
write: pid -1: Bad file descriptor
tah 349
hrac 1'UP'
tah 350
hrac 1'LEFT'
tah 351
hrac 1'LEFT'
tah 352
hrac 1'LEFT'
tah 353
hrac 1'DOWN'
tah 354
hrac 1'DOWN'
tah 355
hrac 1'RIGHT'
tah 356
hrac 1'RIGHT'
ukoncujem klientov
[21:19:16.879] 
