[21:19:17.020] startujem server, seed je 1765350526
main: prepisujem zaznamovy adresar: zaznamy/000010
[21:19:17.022] restartujem klienta paulinia
[21:19:17.022] restartujem klienta m
[21:19:17.022] restartujem klienta okno
[21:19:17.024] restartujem klienta nulano
tah 0
hrac 0'UP'
hrac 1'LEFT'
hrac 2'DOWN'
hrac 3'LEFT'
tah 1
hrac 3'LEFT'
hrac 1'LEFT'
hrac 2'DOWN'
hrac 0'UP'
tah 2
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 3
hrac 3'LEFT'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 4
hrac 1'UP'
hrac 3'LEFT'
hrac 2'UP'
hrac 0'DOWN'
tah 5
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 6
hrac 3'DOWN'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 7
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'DOWN'
tah 8
hrac 3'DOWN'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'DOWN'
tah 9
hrac 3'UP'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'LEFT'
tah 10
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'UP'
tah 11
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'UP'
tah 12
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'DOWN'
tah 13
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'DOWN'
tah 14
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'DOWN'
tah 15
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'LEFT'
tah 16
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 17
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'DOWN'
tah 18
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'RIGHT'
tah 19
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'RIGHT'
tah 20
hrac 3'DOWN'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 21
hrac 3'UP'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'UP'
tah 22
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'UP'
tah 23
hrac 3'UP'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'UP'
tah 24
hrac 1'DOWN'
hrac 3'RIGHT'
hrac 2'LEFT'
hrac 0'DOWN'
tah 25
hrac 3'UP'
hrac 1'DOWN'
hrac 2'DOWN'
hrac 0'DOWN'
tah 26
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 2'DOWN'
hrac 0'DOWN'
tah 27
hrac 3'LEFT'
hrac 1'UP'
hrac 2'DOWN'
hrac 0'DOWN'
tah 28
hrac 3'UP'
hrac 1'RIGHT'
hrac 2'DOWN'
hrac 0'DOWN'
tah 29
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 0'DOWN'
tah 30
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'LEFT'
tah 31
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'LEFT'
tah 32
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'UP'
tah 33
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'UP'
tah 34
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 35
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'RIGHT'
tah 36
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 37
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'DOWN'
tah 38
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'DOWN'
tah 39
hrac 3'LEFT'
hrac 1'DOWN'
hrac 2'RIGHT'
hrac 0'UP'
tah 40
hrac 3'DOWN'
hrac 1'DOWN'
hrac 2'UP'
hrac 0'UP'
tah 41
hrac 3'LEFT'
hrac 1'LEFT'
hrac 2'UP'
hrac 0'UP'
tah 42
hrac 3'DOWN'
hrac 1'UP'
hrac 2'DOWN'
hrac 0'RIGHT'
tah 43
hrac 3'UP'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'UP'
tah 44
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 2'DOWN'
hrac 0'RIGHT'
tah 45
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 46
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 47
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 48
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 49
hrac 3'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 50
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 51
hrac 3'DOWN'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 52
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 53
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 54
hrac 3'DOWN'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'UP'
tah 55
hrac 3'UP'
hrac 1'UP'
hrac 2'UP'
hrac 0'LEFT'
tah 56
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'UP'
tah 57
hrac 1'UP'
hrac 3'UP'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 58
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 59
hrac 3'LEFT'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'UP'
tah 60
hrac 3'UP'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'LEFT'
tah 61
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'LEFT'
tah 62
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 63
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 64
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 65
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 66
hrac 3'DOWN'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'UP'
tah 67
hrac 3'DOWN'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'UP'
tah 68
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 69
hrac 3'DOWN'
hrac 1'UP'
hrac 0'UP'
hrac 2'RIGHT'
tah 70
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 2'UP'
hrac 0'LEFT'
tah 71
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 0'UP'
tah 72
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 2'UP'
hrac 0'UP'
tah 73
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 74
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'RIGHT'
tah 75
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 76
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'DOWN'
tah 77
hrac 1'RIGHT'
hrac 3'LEFT'
hrac 0'UP'
hrac 2'RIGHT'
tah 78
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'UP'
tah 79
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'UP'
tah 80
hrac 1'DOWN'
hrac 3'LEFT'
hrac 0'RIGHT'
hrac 2'UP'
tah 81
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'LEFT'
tah 82
hrac 3'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 83
hrac 3'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 84
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 85
hrac 1'UP'
hrac 3'UP'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 86
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 87
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 88
hrac 3'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 89
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 90
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'DOWN'
tah 91
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 92
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 93
hrac 3'UP'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 94
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'UP'
hrac 2'RIGHT'
tah 95
hrac 3'UP'
hrac 1'UP'
hrac 2'UP'
hrac 0'UP'
tah 96
hrac 3'LEFT'
hrac 1'LEFT'
hrac 2'UP'
hrac 0'LEFT'
tah 97
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 98
hrac 3'UP'
hrac 1'LEFT'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 99
hrac 3'LEFT'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 100
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'UP'
tah 101
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'UP'
tah 102
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'DOWN'
tah 103
hrac 3'DOWN'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'DOWN'
tah 104
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 105
hrac 3'UP'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 106
hrac 3'LEFT'
hrac 1'LEFT'
hrac 2'DOWN'
hrac 0'DOWN'
tah 107
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'LEFT'
tah 108
hrac 3'UP'
hrac 1'DOWN'
hrac 2'LEFT'
hrac 0'DOWN'
tah 109
hrac 3'DOWN'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 110
hrac 3'UP'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'LEFT'
tah 111
hrac 3'UP'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'LEFT'
tah 112
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'DOWN'
hrac 0'UP'
tah 113
hrac 3'UP'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'UP'
tah 114
hrac 3'DOWN'
hrac 1'LEFT'
hrac 2'DOWN'
hrac 0'RIGHT'
tah 115
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 2'LEFT'
hrac 0'UP'
tah 116
hrac 3'UP'
hrac 1'DOWN'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 117
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 118
hrac 3'UP'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 119
hrac 3'DOWN'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 120
hrac 3'UP'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 121
hrac 3'UP'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 122
hrac 3'DOWN'
hrac 1'LEFT'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 123
hrac 3'LEFT'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 124
hrac 3'DOWN'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 125
hrac 3'UP'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 126
hrac 3'UP'
hrac 1'LEFT'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 127
hrac 3'DOWN'
hrac 1'LEFT'
hrac 2'DOWN'
hrac 0'DOWN'
tah 128
hrac 3'LEFT'
hrac 1'DOWN'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 129
hrac 3'DOWN'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'UP'
tah 130
hrac 3'LEFT'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'UP'
tah 131
hrac 3'DOWN'
hrac 1'DOWN'
hrac 2'LEFT'
hrac 0'LEFT'
tah 132
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'LEFT'
tah 133
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'LEFT'
tah 134
hrac 1'LEFT'
hrac 3'UP'
hrac 2'UP'
hrac 0'LEFT'
tah 135
hrac 3'UP'
hrac 1'LEFT'
hrac 2'UP'
hrac 0'LEFT'
tah 136
hrac 1'LEFT'
hrac 3'RIGHT'
hrac 2'UP'
hrac 0'LEFT'
tah 137
hrac 3'UP'
hrac 1'LEFT'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 138
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 139
hrac 3'UP'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 140
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 141
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 142
hrac 3'UP'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 143
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'DOWN'
tah 144
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'DOWN'
tah 145
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'DOWN'
tah 146
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'LEFT'
tah 147
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'UP'
tah 148
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'UP'
tah 149
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'UP'
tah 150
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 151
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 152
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 153
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 154
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 155
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 156
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 157
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 158
hrac 3'UP'
hrac 0'RIGHT'
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 159
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 160
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'UP'
tah 161
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'UP'
tah 162
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'UP'
tah 163
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'LEFT'
tah 164
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'LEFT'
tah 165
hrac 3'UP'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'DOWN'
tah 166
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 167
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 168
hrac 1'DOWN'
hrac 3'RIGHT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 169
hrac 1'RIGHT'
hrac 3'LEFT'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 170
hrac 3'UP'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'RIGHT'
tah 171
hrac 1'DOWN'
hrac 3'DOWN'
hrac 0'UP'
hrac 2'UP'
tah 172
hrac 1'RIGHT'
hrac 3'RIGHT'
hrac 0'RIGHT'
hrac 2'UP'
tah 173
hrac 1'RIGHT'
hrac 3'RIGHT'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 174
hrac 3'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 175
hrac 3'UP'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'UP'
tah 176
hrac 1'UP'
hrac 3'LEFT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 177
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 0'DOWN'
tah 178
hrac 1'DOWN'
hrac 3'DOWN'
hrac 2'LEFT'
hrac 0'DOWN'
tah 179
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'UP'
tah 180
hrac 1'RIGHT'
hrac 3'DOWN'
hrac 0'DOWN'
hrac 2'UP'
tah 181
hrac 1'LEFT'
hrac 3'LEFT'
hrac 2'UP'
hrac 0'RIGHT'
tah 182
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'UP'
hrac 0'DOWN'
tah 183
hrac 3'UP'
hrac 1'DOWN'
hrac 2'UP'
hrac 0'DOWN'
tah 184
hrac 3'UP'
hrac 1'DOWN'
hrac 2'UP'
hrac 0'DOWN'
tah 185
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'UP'
tah 186
hrac 1'DOWN'
hrac 3'UP'
hrac 2'UP'
hrac 0'DOWN'
tah 187
hrac 3'DOWN'
hrac 1'LEFT'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 188
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 189
hrac 1'LEFT'
hrac 3'UP'
hrac 2'UP'
hrac 0'DOWN'
tah 190
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'UP'
tah 191
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'UP'
tah 192
hrac 3'DOWN'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'UP'
tah 193
hrac 1'UP'
hrac 3'LEFT'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 194
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'UP'
hrac 0'DOWN'
tah 195
hrac 1'UP'
hrac 3'DOWN'
hrac 2'UP'
hrac 0'DOWN'
tah 196
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 2'UP'
hrac 0'DOWN'
tah 197
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 198
hrac 3'LEFT'
hrac 1'LEFT'
hrac 2'UP'
hrac 0'LEFT'
tah 199
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'UP'
hrac 0'LEFT'
tah 200
hrac 3'UP'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 201
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 202
hrac 3'UP'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 203
hrac 3'UP'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 204
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'DOWN'
tah 205
hrac 3'LEFT'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'DOWN'
tah 206
hrac 3'DOWN'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'LEFT'
tah 207
hrac 3'DOWN'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'LEFT'
tah 208
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'DOWN'
hrac 0'LEFT'
tah 209
hrac 3'DOWN'
hrac 1'LEFT'
hrac 2'DOWN'
hrac 0'UP'
tah 210
hrac 3'LEFT'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'DOWN'
tah 211
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'DOWN'
hrac 0'UP'
tah 212
hrac 3'DOWN'
hrac 1'UP'
hrac 2'DOWN'
hrac 0'UP'
tah 213
hrac 3'LEFT'
hrac 1'UP'
hrac 0'UP'
hrac 2'DOWN'
tah 214
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'DOWN'
hrac 0'UP'
tah 215
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 2'DOWN'
hrac 0'UP'
tah 216
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'DOWN'
tah 217
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'DOWN'
tah 218
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'LEFT'
tah 219
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'LEFT'
tah 220
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'DOWN'
tah 221
hrac 3'UP'
hrac 1'DOWN'
hrac 2'RIGHT'
hrac 0'UP'
tah 222
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 223
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'DOWN'
tah 224
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 3'DOWN'
hrac 0'UP'
tah 225
hrac 1'DOWN'
hrac 3'RIGHT'
hrac 2'UP'
hrac 0'LEFT'
tah 226
hrac 3'DOWN'
hrac 1'DOWN'
hrac 2'UP'
hrac 0'LEFT'
tah 227
hrac 3'LEFT'
hrac 1'DOWN'
hrac 2'DOWN'
hrac 0'DOWN'
tah 228
hrac 3'UP'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'DOWN'
tah 229
hrac 3'LEFT'
hrac 1'DOWN'
hrac 2'DOWN'
hrac 0'DOWN'
tah 230
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 231
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 232
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 233
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 234
hrac 3'LEFT'
hrac 1'DOWN'
hrac 2'LEFT'
hrac 0'DOWN'
tah 235
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'DOWN'
tah 236
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'DOWN'
tah 237
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 238
hrac 3'UP'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'UP'
tah 239
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'UP'
tah 240
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'DOWN'
tah 241
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 242
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'RIGHT'
tah 243
hrac 1'DOWN'
hrac 3'DOWN'
hrac 2'DOWN'
hrac 0'LEFT'
tah 244
hrac 1'DOWN'
hrac 3'RIGHT'
hrac 2'LEFT'
hrac 0'LEFT'
tah 245
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'DOWN'
tah 246
hrac 1'RIGHT'
hrac 3'RIGHT'
hrac 2'RIGHT'
hrac 0'UP'
tah 247
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'RIGHT'
tah 248
hrac 1'RIGHT'
hrac 3'LEFT'
hrac 2'UP'
hrac 0'UP'
tah 249
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 0'UP'
tah 250
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 2'DOWN'
hrac 0'LEFT'
tah 251
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 252
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 0'UP'
tah 253
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'RIGHT'
tah 254
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'RIGHT'
tah 255
hrac 3'LEFT'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'UP'
tah 256
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'UP'
tah 257
hrac 3'DOWN'
hrac 1'UP'
hrac 0'UP'
hrac 2'LEFT'
tah 258
hrac 3'LEFT'
hrac 1'UP'
hrac 0'UP'
hrac 2'LEFT'
tah 259
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 260
hrac 3'LEFT'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'LEFT'
tah 261
hrac 3'LEFT'
hrac 1'UP'
hrac 0'UP'
hrac 2'UP'
tah 262
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'LEFT'
tah 263
hrac 3'LEFT'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'LEFT'
tah 264
hrac 3'LEFT'
hrac 1'UP'
hrac 0'UP'
hrac 2'UP'
tah 265
hrac 1'LEFT'
hrac 3'RIGHT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 266
hrac 1'LEFT'
hrac 3'UP'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 267
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 268
hrac 3'UP'
hrac 1'LEFT'
hrac 2'DOWN'
hrac 0'RIGHT'
tah 269
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'DOWN'
hrac 0'RIGHT'
tah 270
hrac 3'LEFT'
hrac 1'UP'
hrac 2'DOWN'
hrac 0'RIGHT'
tah 271
hrac 3'LEFT'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 272
hrac 3'DOWN'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 273
hrac 3'LEFT'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 274
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 0'UP'
tah 275
hrac 3'LEFT'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'UP'
tah 276
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 277
hrac 3'LEFT'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 278
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 0'DOWN'
tah 279
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 280
hrac 3'UP'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 281
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 282
hrac 3'UP'
hrac 1'DOWN'
hrac 2'LEFT'
hrac 0'UP'
tah 283
hrac 3'UP'
hrac 1'DOWN'
hrac 2'LEFT'
hrac 0'UP'
tah 284
hrac 3'DOWN'
hrac 1'DOWN'
hrac 2'LEFT'
hrac 0'LEFT'
tah 285
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 286
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 287
hrac 3'LEFT'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'LEFT'
tah 288
hrac 3'UP'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'DOWN'
tah 289
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'DOWN'
tah 290
hrac 3'UP'
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 291
hrac 3'DOWN'
hrac 1'DOWN'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 292
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 2'LEFT'
hrac 0'LEFT'
tah 293
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 0'LEFT'
tah 294
hrac 3'UP'
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 295
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 0'LEFT'
tah 296
hrac 3'UP'
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 0'LEFT'
tah 297
hrac 3'LEFT'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'DOWN'
tah 298
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 0'UP'
tah 299
hrac 3'LEFT'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'LEFT'
tah 300
hrac 3'LEFT'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'UP'
tah 301
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 302
hrac 3'UP'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 303
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 304
hrac 3'LEFT'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 305
hrac 3'UP'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 306
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 307
hrac 3'UP'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 308
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'RIGHT'
tah 309
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 2'UP'
hrac 0'UP'
tah 310
hrac 3'LEFT'
hrac 1'DOWN'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 311
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 312
hrac 1'DOWN'
hrac 3'DOWN'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 313
hrac 1'RIGHT'
hrac 3'LEFT'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 314
hrac 1'RIGHT'
hrac 3'DOWN'
hrac 2'UP'
hrac 0'RIGHT'
tah 315
hrac 1'UP'
hrac 3'LEFT'
hrac 2'RIGHT'
hrac 0'DOWN'
tah 316
hrac 3'RIGHT'
hrac 1'UP'
hrac 2'UP'
hrac 0'RIGHT'
tah 317
hrac 1'UP'
hrac 3'LEFT'
hrac 2'UP'
hrac 0'DOWN'
tah 318
hrac 1'RIGHT'
hrac 3'UP'
hrac 2'UP'
hrac 0'DOWN'
tah 319
hrac 3'DOWN'
hrac 1'DOWN'
hrac 2'UP'
hrac 0'DOWN'
tah 320
hrac 3'LEFT'
hrac 1'DOWN'
hrac 2'UP'
hrac 0'DOWN'
tah 321
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'UP'
tah 322
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'UP'
tah 323
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'UP'
tah 324
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'UP'
tah 325
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'RIGHT'
tah 326
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'UP'
tah 327
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'UP'
tah 328
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'UP'
tah 329
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'UP'
tah 330
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'RIGHT'
tah 331
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'UP'
tah 332
hrac 3'UP'
hrac 1'UP'
hrac 0'UP'
hrac 2'RIGHT'
tah 333
hrac 3'LEFT'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'UP'
tah 334
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'UP'
tah 335
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 336
hrac 3'UP'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'UP'
tah 337
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'UP'
tah 338
hrac 3'UP'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 339
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'UP'
tah 340
hrac 3'UP'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 341
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 342
hrac 3'UP'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 343
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 344
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'DOWN'
tah 345
hrac 3'UP'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'LEFT'
tah 346
hrac 3'DOWN'
hrac 1'UP'
hrac 0'UP'
hrac 2'LEFT'
tah 347
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'DOWN'
tah 348
hrac 3'UP'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 349
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 350
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 351
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 352
hrac 1'RIGHT'
hrac 3'LEFT'
hrac 2'DOWN'
hrac 0'RIGHT'
tah 353
hrac 1'RIGHT'
hrac 3'UP'
hrac 2'DOWN'
hrac 0'RIGHT'
tah 354
hrac 3'DOWN'
hrac 1'UP'
hrac 2'DOWN'
hrac 0'RIGHT'
tah 355
hrac 1'UP'
hrac 3'UP'
hrac 2'DOWN'
hrac 0'RIGHT'
tah 356
hrac 3'LEFT'
hrac 1'UP'
hrac 2'DOWN'
hrac 0'RIGHT'
tah 357
hrac 3'DOWN'
hrac 1'UP'
hrac 2'DOWN'
hrac 0'DOWN'
tah 358
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 359
hrac 3'UP'
hrac 1'DOWN'
hrac 2'DOWN'
hrac 0'DOWN'
tah 360
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 2'LEFT'
hrac 0'DOWN'
tah 361
hrac 3'UP'
hrac 1'RIGHT'
hrac 2'DOWN'
hrac 0'LEFT'
tah 362
hrac 3'DOWN'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'LEFT'
tah 363
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 364
hrac 3'UP'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'DOWN'
tah 365
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'DOWN'
tah 366
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 367
hrac 3'DOWN'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'DOWN'
tah 368
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'DOWN'
tah 369
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'DOWN'
tah 370
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'LEFT'
tah 371
hrac 3'UP'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'LEFT'
tah 372
hrac 3'UP'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'LEFT'
tah 373
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 374
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 375
hrac 3'UP'
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 0'DOWN'
tah 376
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'LEFT'
tah 377
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'LEFT'
tah 378
hrac 3'LEFT'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'LEFT'
tah 379
hrac 3'DOWN'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'LEFT'
tah 380
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'LEFT'
tah 381
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'LEFT'
tah 382
hrac 3'UP'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'LEFT'
tah 383
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'LEFT'
tah 384
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 0'DOWN'
tah 385
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'LEFT'
tah 386
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'LEFT'
tah 387
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'LEFT'
tah 388
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'LEFT'
tah 389
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'LEFT'
tah 390
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'UP'
tah 391
hrac 3'LEFT'
hrac 0'LEFT'
hrac 1'RIGHT'
hrac 2'RIGHT'
tah 392
hrac 3'LEFT'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 393
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 394
hrac 3'LEFT'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 395
hrac 3'LEFT'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 396
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'RIGHT'
tah 397
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 398
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 399
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 400
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 401
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'RIGHT'
tah 402
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 403
hrac 3'LEFT'
hrac 1'UP'
hrac 0'UP'
hrac 2'LEFT'
tah 404
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'LEFT'
tah 405
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'UP'
tah 406
hrac 3'DOWN'
hrac 0'UP'
hrac 1'UP'
hrac 2'UP'
tah 407
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'RIGHT'
tah 408
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 409
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 410
hrac 3'UP'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 411
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 412
hrac 3'UP'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'DOWN'
tah 413
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'DOWN'
tah 414
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 415
hrac 3'UP'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 416
hrac 3'UP'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 417
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 418
hrac 3'UP'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 419
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 420
hrac 3'UP'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 421
hrac 3'UP'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'LEFT'
tah 422
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 423
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'LEFT'
tah 424
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 425
hrac 3'LEFT'
hrac 1'LEFT'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 426
hrac 3'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 427
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 428
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 429
hrac 3'DOWN'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 430
hrac 3'UP'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 431
hrac 3'UP'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'RIGHT'
tah 432
hrac 3'DOWN'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'UP'
tah 433
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'UP'
tah 434
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 435
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'RIGHT'
hrac 2'UP'
tah 436
hrac 3'UP'
hrac 1'UP'
hrac 0'UP'
hrac 2'RIGHT'
tah 437
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'UP'
tah 438
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'UP'
tah 439
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'UP'
tah 440
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'UP'
tah 441
hrac 1'DOWN'
hrac 3'DOWN'
hrac 0'UP'
hrac 2'UP'
tah 442
hrac 3'LEFT'
hrac 1'LEFT'
hrac 2'UP'
hrac 0'RIGHT'
tah 443
hrac 1'UP'
hrac 3'RIGHT'
hrac 2'UP'
hrac 0'UP'
tah 444
hrac 1'UP'
hrac 3'UP'
hrac 0'UP'
hrac 2'UP'
tah 445
hrac 1'LEFT'
hrac 3'UP'
hrac 0'UP'
hrac 2'RIGHT'
tah 446
hrac 1'LEFT'
hrac 3'DOWN'
hrac 0'UP'
hrac 2'UP'
tah 447
hrac 1'LEFT'
hrac 3'LEFT'
hrac 0'UP'
hrac 2'UP'
tah 448
hrac 1'LEFT'
hrac 3'DOWN'
hrac 0'UP'
hrac 2'UP'
tah 449
hrac 1'LEFT'
hrac 3'DOWN'
hrac 0'LEFT'
hrac 2'UP'
tah 450
hrac 1'LEFT'
hrac 3'RIGHT'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 451
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'UP'
tah 452
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 2'RIGHT'
hrac 0'RIGHT'
tah 453
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'UP'
tah 454
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'UP'
tah 455
hrac 1'LEFT'
hrac 3'DOWN'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 456
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'UP'
tah 457
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'UP'
tah 458
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'RIGHT'
tah 459
hrac 1'RIGHT'
hrac 3'LEFT'
hrac 0'UP'
hrac 2'UP'
tah 460
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'UP'
hrac 2'RIGHT'
tah 461
hrac 3'UP'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'UP'
tah 462
hrac 1'LEFT'
hrac 3'RIGHT'
hrac 0'UP'
hrac 2'RIGHT'
tah 463
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'RIGHT'
tah 464
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'RIGHT'
tah 465
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'DOWN'
tah 466
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'LEFT'
tah 467
hrac 3'UP'
hrac 0'UP'
hrac 1'LEFT'
hrac 2'DOWN'
tah 468
hrac 1'LEFT'
hrac 3'LEFT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 469
hrac 1'LEFT'
hrac 3'RIGHT'
hrac 0'UP'
hrac 2'LEFT'
tah 470
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 471
hrac 1'LEFT'
hrac 3'UP'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 472
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'DOWN'
tah 473
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'LEFT'
tah 474
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'DOWN'
tah 475
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'DOWN'
tah 476
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'DOWN'
tah 477
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'DOWN'
tah 478
hrac 3'UP'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'DOWN'
tah 479
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'DOWN'
tah 480
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 481
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'DOWN'
tah 482
hrac 3'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 483
hrac 3'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 484
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 485
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'DOWN'
tah 486
hrac 1'RIGHT'
hrac 3'UP'
hrac 0'LEFT'
hrac 2'LEFT'
tah 487
hrac 1'LEFT'
hrac 3'UP'
hrac 2'DOWN'
hrac 0'UP'
tah 488
hrac 1'UP'
hrac 3'LEFT'
hrac 2'DOWN'
hrac 0'UP'
tah 489
hrac 1'LEFT'
hrac 3'RIGHT'
hrac 2'DOWN'
hrac 0'UP'
tah 490
hrac 1'DOWN'
hrac 3'LEFT'
hrac 2'DOWN'
hrac 0'UP'
tah 491
hrac 1'UP'
hrac 3'LEFT'
hrac 0'UP'
hrac 2'DOWN'
tah 492
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'UP'
hrac 2'DOWN'
tah 493
hrac 1'LEFT'
hrac 3'DOWN'
hrac 2'DOWN'
hrac 0'UP'
tah 494
hrac 1'RIGHT'
hrac 3'DOWN'
hrac 0'UP'
hrac 2'LEFT'
tah 495
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'LEFT'
tah 496
hrac 1'RIGHT'
hrac 3'DOWN'
hrac 2'LEFT'
hrac 0'UP'
tah 497
hrac 1'LEFT'
hrac 3'RIGHT'
hrac 2'LEFT'
hrac 0'UP'
tah 498
hrac 1'LEFT'
hrac 3'DOWN'
hrac 2'UP'
hrac 0'LEFT'
tah 499
hrac 1'DOWN'
hrac 3'DOWN'
hrac 2'UP'
hrac 0'LEFT'
tah 500
hrac 1'LEFT'
hrac 3'UP'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 501
hrac 1'LEFT'
hrac 3'LEFT'
hrac 2'UP'
hrac 0'LEFT'
tah 502
hrac 1'LEFT'
hrac 3'RIGHT'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 503
hrac 3'DOWN'
hrac 1'LEFT'
hrac 2'UP'
hrac 0'LEFT'
tah 504
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'UP'
tah 505
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'UP'
tah 506
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'UP'
tah 507
hrac 3'UP'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'UP'
tah 508
hrac 3'DOWN'
hrac 1'DOWN'
hrac 2'UP'
hrac 0'LEFT'
tah 509
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'UP'
tah 510
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'UP'
tah 511
hrac 3'DOWN'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 512
hrac 1'UP'
hrac 3'UP'
hrac 2'UP'
hrac 0'UP'
tah 513
hrac 1'UP'
hrac 3'DOWN'
hrac 2'UP'
hrac 0'LEFT'
tah 514
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 2'UP'
hrac 0'LEFT'
tah 515
hrac 3'UP'
hrac 1'RIGHT'
hrac 2'UP'
hrac 0'LEFT'
tah 516
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 0'DOWN'
tah 517
hrac 1'DOWN'
hrac 3'RIGHT'
hrac 2'UP'
hrac 0'DOWN'
tah 518
hrac 3'DOWN'
hrac 1'UP'
hrac 2'RIGHT'
hrac 0'DOWN'
tah 519
hrac 3'LEFT'
hrac 1'LEFT'
hrac 2'UP'
hrac 0'DOWN'
tah 520
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'UP'
tah 521
hrac 1'RIGHT'
hrac 3'LEFT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 522
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'UP'
tah 523
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'UP'
tah 524
hrac 3'UP'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'RIGHT'
tah 525
hrac 3'UP'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'UP'
tah 526
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'RIGHT'
tah 527
hrac 3'LEFT'
hrac 1'UP'
hrac 0'UP'
hrac 2'UP'
tah 528
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 529
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'UP'
tah 530
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 531
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'RIGHT'
tah 532
hrac 3'UP'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 533
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 534
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 535
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 536
hrac 3'UP'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 537
hrac 3'UP'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'LEFT'
tah 538
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 539
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'UP'
hrac 2'UP'
tah 540
hrac 1'UP'
hrac 3'RIGHT'
hrac 0'LEFT'
tah 541
hrac 2'UP'
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'UP'
tah 542
hrac 1'RIGHT'
hrac 3'UP'
hrac 2'RIGHT'
hrac 0'LEFT'
tah 543
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 544
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 545
hrac 1'UP'
hrac 3'LEFT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 546
hrac 3'UP'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'DOWN'
tah 547
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'LEFT'
hrac 2'LEFT'
tah 548
hrac 1'DOWN'
hrac 3'RIGHT'
hrac 0'DOWN'
hrac 2'LEFT'
tah 549
hrac 1'DOWN'
hrac 3'UP'
hrac 0'LEFT'
hrac 2'DOWN'
tah 550
hrac 1'DOWN'
hrac 3'LEFT'
hrac 0'DOWN'
hrac 2'DOWN'
tah 551
hrac 1'DOWN'
hrac 3'LEFT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 552
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'DOWN'
hrac 2'UP'
tah 553
hrac 1'DOWN'
hrac 3'LEFT'
hrac 0'DOWN'
hrac 2'UP'
tah 554
hrac 1'DOWN'
hrac 3'RIGHT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 555
hrac 1'DOWN'
hrac 3'UP'
hrac 0'UP'
hrac 2'RIGHT'
tah 556
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 557
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'UP'
hrac 2'DOWN'
tah 558
hrac 3'LEFT'
hrac 1'UP'
hrac 0'UP'
hrac 2'DOWN'
tah 559
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'UP'
hrac 2'LEFT'
tah 560
hrac 3'DOWN'
hrac 1'UP'
hrac 0'RIGHT'
hrac 2'UP'
tah 561
hrac 1'RIGHT'
hrac 3'RIGHT'
hrac 0'RIGHT'
hrac 2'UP'
tah 562
hrac 1'LEFT'
hrac 3'DOWN'
hrac 0'UP'
hrac 2'UP'
tah 563
hrac 1'UP'
hrac 3'LEFT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 564
hrac 1'RIGHT'
hrac 3'UP'
hrac 0'DOWN'
hrac 2'DOWN'
tah 565
hrac 1'LEFT'
hrac 3'LEFT'
hrac 2'DOWN'
hrac 0'UP'
tah 566
hrac 1'LEFT'
hrac 3'UP'
hrac 0'UP'
hrac 2'DOWN'
tah 567
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'LEFT'
tah 568
hrac 1'LEFT'
hrac 3'RIGHT'
hrac 2'LEFT'
hrac 0'DOWN'
tah 569
hrac 1'RIGHT'
hrac 3'UP'
hrac 0'LEFT'
hrac 2'DOWN'
tah 570
hrac 1'RIGHT'
hrac 3'RIGHT'
hrac 0'DOWN'
hrac 2'DOWN'
tah 571
hrac 1'LEFT'
hrac 3'UP'
hrac 0'LEFT'
hrac 2'DOWN'
tah 572
hrac 1'LEFT'
hrac 3'DOWN'
hrac 0'UP'
hrac 2'RIGHT'
tah 573
hrac 1'UP'
hrac 3'LEFT'
hrac 0'RIGHT'
hrac 2'RIGHT'
tah 574
hrac 3'LEFT'
hrac 1'UP'
hrac 0'UP'
hrac 2'DOWN'
tah 575
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'LEFT'
hrac 2'LEFT'
tah 576
hrac 1'UP'
hrac 3'UP'
hrac 0'UP'
hrac 2'DOWN'
tah 577
hrac 1'UP'
hrac 3'DOWN'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 578
hrac 1'UP'
hrac 3'LEFT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 579
hrac 1'DOWN'
hrac 3'LEFT'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 580
hrac 1'UP'
hrac 3'RIGHT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 581
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'DOWN'
tah 582
hrac 1'RIGHT'
hrac 3'RIGHT'
hrac 0'DOWN'
hrac 2'DOWN'
tah 583
hrac 3'UP'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'DOWN'
tah 584
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 585
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 586
hrac 1'DOWN'
hrac 3'LEFT'
hrac 0'DOWN'
hrac 2'DOWN'
tah 587
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'LEFT'
tah 588
hrac 1'DOWN'
hrac 3'DOWN'
hrac 0'UP'
hrac 2'DOWN'
tah 589
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'LEFT'
tah 590
hrac 1'LEFT'
hrac 3'DOWN'
hrac 0'LEFT'
hrac 2'DOWN'
tah 591
hrac 1'UP'
hrac 3'RIGHT'
hrac 0'UP'
hrac 2'LEFT'
tah 592
hrac 3'DOWN'
hrac 1'UP'
hrac 0'UP'
hrac 2'DOWN'
tah 593
hrac 1'UP'
hrac 3'RIGHT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 594
hrac 1'UP'
hrac 3'LEFT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 595
hrac 1'LEFT'
hrac 3'LEFT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 596
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'DOWN'
hrac 2'DOWN'
tah 597
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'DOWN'
tah 598
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 599
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
hrac 2'RIGHT'
tah 600
hrac 1'DOWN'
hrac 3'UP'
hrac 0'UP'
hrac 2'LEFT'
tah 601
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2'LEFT'
tah 602
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'RIGHT'
hrac 2'LEFT'
tah 603
hrac 3'UP'
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 0'RIGHT'
tah 604
hrac 3'UP'
hrac 1'UP'
hrac 0'UP'
hrac 2'RIGHT'
tah 605
hrac 3'UP'
hrac 1'LEFT'
hrac 0'DOWN'
hrac 2'RIGHT'
tah 606
hrac 3'UP'
hrac 1'LEFT'
hrac 2'UP'
hrac 0'UP'
tah 607
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'LEFT'
hrac 2'UP'
hraci 0 a 1 sa celne zrazili
proces 29799 umrel na: Terminated
proces 29800 umrel na: Terminated
write: pid -1: Bad file descriptor
write: pid -1: Bad file descriptor
tah 608
hrac 3'UP'
hrac 2'UP'
tah 609
hrac 3'UP'
hrac 2'UP'
tah 610
hrac 3'DOWN'
hrac 2'UP'
tah 611
hrac 3'LEFT'
hrac 2'UP'
tah 612
hrac 3'RIGHT'
hrac 2'UP'
tah 613
hrac 3'UP'
hrac 2'UP'
tah 614
hrac 3'UP'
hrac 2'UP'
tah 615
hrac 3'DOWN'
hrac 2'UP'
tah 616
hrac 3'LEFT'
hrac 2'UP'
tah 617
hrac 3'DOWN'
hrac 2'UP'
tah 618
hrac 3'RIGHT'
hrac 2'UP'
tah 619
hrac 3'RIGHT'
hrac 2'UP'
tah 620
hrac 3'RIGHT'
hrac 2'UP'
tah 621
hrac 3'DOWN'
hrac 2'UP'
tah 622
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 623
hrac 3'DOWN'
hrac 2'UP'
tah 624
hrac 3'RIGHT'
hrac 2'UP'
tah 625
hrac 3'UP'
hrac 2'RIGHT'
tah 626
hrac 3'DOWN'
hrac 2'UP'
tah 627
hrac 3'RIGHT'
hrac 2'UP'
tah 628
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 629
hrac 3'LEFT'
hrac 2'UP'
tah 630
hrac 3'UP'
hrac 2'RIGHT'
tah 631
hrac 3'DOWN'
hrac 2'UP'
tah 632
hrac 3'UP'
hrac 2'RIGHT'
tah 633
hrac 3'UP'
hrac 2'UP'
tah 634
hrac 3'DOWN'
hrac 2'RIGHT'
tah 635
hrac 3'LEFT'
hrac 2'UP'
tah 636
hrac 3'UP'
hrac 2'RIGHT'
tah 637
hrac 3'RIGHT'
hrac 2'UP'
tah 638
hrac 3'UP'
hrac 2'RIGHT'
tah 639
hrac 3'DOWN'
hrac 2'RIGHT'
tah 640
hrac 3'UP'
hrac 2'RIGHT'
tah 641
hrac 3'LEFT'
hrac 2'DOWN'
tah 642
hrac 3'DOWN'
hrac 2'DOWN'
tah 643
hrac 3'LEFT'
hrac 2'DOWN'
tah 644
hrac 3'DOWN'
hrac 2'DOWN'
tah 645
hrac 3'UP'
hrac 2'UP'
tah 646
hrac 3'UP'
hrac 2'UP'
tah 647
hrac 3'RIGHT'
hrac 2'LEFT'
tah 648
hrac 3'UP'
hrac 2'DOWN'
tah 649
hrac 3'DOWN'
hrac 2'DOWN'
tah 650
hrac 3'UP'
hrac 2'DOWN'
tah 651
hrac 3'UP'
hrac 2'DOWN'
tah 652
hrac 3'DOWN'
hrac 2'DOWN'
tah 653
hrac 3'LEFT'
hrac 2'LEFT'
tah 654
hrac 3'DOWN'
hrac 2'DOWN'
tah 655
hrac 3'LEFT'
hrac 2'LEFT'
tah 656
hrac 3'DOWN'
hrac 2'DOWN'
tah 657
hrac 3'LEFT'
hrac 2'LEFT'
tah 658
hrac 3'UP'
hrac 2'DOWN'
tah 659
hrac 3'RIGHT'
hrac 2'DOWN'
tah 660
hrac 3'UP'
hrac 2'DOWN'
tah 661
hrac 3'RIGHT'
hrac 2'DOWN'
tah 662
hrac 3'UP'
hrac 2'LEFT'
tah 663
hrac 3'RIGHT'
hrac 2'DOWN'
tah 664
hrac 3'UP'
hrac 2'DOWN'
tah 665
hrac 3'DOWN'
hrac 2'DOWN'
tah 666
hrac 3'RIGHT'
hrac 2'LEFT'
tah 667
hrac 3'DOWN'
hrac 2'DOWN'
tah 668
hrac 3'UP'
hrac 2'LEFT'
tah 669
hrac 3'UP'
hrac 2'DOWN'
tah 670
hrac 3'RIGHT'
hrac 2'LEFT'
tah 671
hrac 3'UP'
hrac 2'DOWN'
tah 672
hrac 3'LEFT'
hrac 2'LEFT'
tah 673
hrac 3'RIGHT'
hrac 2'DOWN'
tah 674
hrac 3'UP'
hrac 2'LEFT'
tah 675
hrac 3'DOWN'
hrac 2'DOWN'
tah 676
hrac 3'LEFT'
hrac 2'DOWN'
tah 677
hrac 3'UP'
hrac 2'DOWN'
tah 678
hrac 3'RIGHT'
hrac 2'DOWN'
tah 679
hrac 3'RIGHT'
hrac 2'DOWN'
tah 680
hrac 3'LEFT'
hrac 2'LEFT'
tah 681
hrac 3'UP'
hrac 2'LEFT'
tah 682
hrac 3'DOWN'
hrac 2'RIGHT'
tah 683
hrac 3'LEFT'
hrac 2'RIGHT'
tah 684
hrac 3'LEFT'
hrac 2'LEFT'
tah 685
hrac 3'RIGHT'
hrac 2'LEFT'
tah 686
hrac 3'UP'
hrac 2'RIGHT'
tah 687
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 688
hrac 3'UP'
hrac 2'RIGHT'
tah 689
hrac 3'DOWN'
hrac 2'RIGHT'
tah 690
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 691
hrac 3'DOWN'
hrac 2'RIGHT'
tah 692
hrac 3'UP'
hrac 2'RIGHT'
tah 693
hrac 3'UP'
hrac 2'RIGHT'
tah 694
hrac 3'RIGHT'
hrac 2'UP'
tah 695
hrac 3'LEFT'
hrac 2'UP'
tah 696
hrac 3'UP'
hrac 2'UP'
tah 697
hrac 3'DOWN'
hrac 2'RIGHT'
tah 698
hrac 3'LEFT'
hrac 2'RIGHT'
tah 699
hrac 3'LEFT'
hrac 2'DOWN'
tah 700
hrac 3'RIGHT'
hrac 2'DOWN'
tah 701
hrac 3'UP'
hrac 2'DOWN'
tah 702
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 703
hrac 3'UP'
hrac 2'RIGHT'
tah 704
hrac 3'DOWN'
hrac 2'LEFT'
tah 705
hrac 3'UP'
hrac 2'LEFT'
tah 706
hrac 3'LEFT'
hrac 2'RIGHT'
tah 707
hrac 3'DOWN'
hrac 2'RIGHT'
tah 708
hrac 3'LEFT'
hrac 2'UP'
tah 709
hrac 3'RIGHT'
hrac 2'UP'
tah 710
hrac 3'UP'
hrac 2'UP'
tah 711
hrac 3'LEFT'
hrac 2'UP'
tah 712
hrac 3'RIGHT'
hrac 2'UP'
tah 713
hrac 3'UP'
hrac 2'UP'
tah 714
hrac 3'DOWN'
hrac 2'UP'
tah 715
hrac 3'LEFT'
hrac 2'UP'
tah 716
hrac 3'UP'
hrac 2'LEFT'
tah 717
hrac 3'DOWN'
hrac 2'LEFT'
tah 718
hrac 3'LEFT'
hrac 2'LEFT'
tah 719
hrac 3'RIGHT'
hrac 2'UP'
tah 720
hrac 3'UP'
hrac 2'UP'
tah 721
hrac 3'LEFT'
hrac 2'UP'
tah 722
hrac 3'DOWN'
hrac 2'RIGHT'
tah 723
hrac 3'LEFT'
hrac 2'RIGHT'
tah 724
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 725
hrac 3'DOWN'
hrac 2'DOWN'
tah 726
hrac 3'RIGHT'
hrac 2'DOWN'
tah 727
hrac 3'LEFT'
hrac 2'DOWN'
tah 728
hrac 3'DOWN'
hrac 2'DOWN'
tah 729
hrac 3'RIGHT'
hrac 2'UP'
tah 730
hrac 3'DOWN'
hrac 2'UP'
tah 731
hrac 3'LEFT'
hrac 2'UP'
tah 732
hrac 3'DOWN'
hrac 2'UP'
tah 733
hrac 3'DOWN'
hrac 2'UP'
tah 734
hrac 3'RIGHT'
hrac 2'DOWN'
tah 735
hrac 3'LEFT'
hrac 2'DOWN'
tah 736
hrac 3'LEFT'
hrac 2'DOWN'
tah 737
hrac 3'RIGHT'
hrac 2'DOWN'
tah 738
hrac 3'DOWN'
hrac 2'DOWN'
tah 739
hrac 3'LEFT'
hrac 2'DOWN'
tah 740
hrac 3'RIGHT'
hrac 2'DOWN'
tah 741
hrac 3'LEFT'
hrac 2'DOWN'
tah 742
hrac 3'LEFT'
hrac 2'LEFT'
tah 743
hrac 3'RIGHT'
hrac 2'DOWN'
tah 744
hrac 3'UP'
hrac 2'DOWN'
tah 745
hrac 3'LEFT'
hrac 2'DOWN'
tah 746
hrac 3'DOWN'
hrac 2'DOWN'
tah 747
hrac 3'DOWN'
hrac 2'RIGHT'
tah 748
hrac 3'UP'
hrac 2'LEFT'
tah 749
hrac 3'LEFT'
hrac 2'LEFT'
tah 750
hrac 3'RIGHT'
hrac 2'LEFT'
tah 751
hrac 3'DOWN'
hrac 2'LEFT'
tah 752
hrac 3'LEFT'
hrac 2'RIGHT'
tah 753
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 754
hrac 3'LEFT'
hrac 2'RIGHT'
tah 755
hrac 3'LEFT'
hrac 2'RIGHT'
tah 756
hrac 3'DOWN'
hrac 2'UP'
tah 757
hrac 3'LEFT'
hrac 2'UP'
tah 758
hrac 3'RIGHT'
hrac 2'UP'
tah 759
hrac 3'UP'
hrac 2'UP'
tah 760
hrac 3'LEFT'
hrac 2'DOWN'
tah 761
hrac 3'DOWN'
hrac 2'DOWN'
tah 762
hrac 3'RIGHT'
hrac 2'DOWN'
tah 763
hrac 3'UP'
hrac 2'DOWN'
tah 764
hrac 3'UP'
hrac 2'LEFT'
tah 765
hrac 3'DOWN'
hrac 2'LEFT'
tah 766
hrac 3'UP'
hrac 2'LEFT'
tah 767
hrac 3'UP'
hrac 2'RIGHT'
tah 768
hrac 3'DOWN'
hrac 2'RIGHT'
tah 769
hrac 3'LEFT'
hrac 2'UP'
tah 770
hrac 3'DOWN'
hrac 2'UP'
tah 771
hrac 3'RIGHT'
hrac 2'UP'
tah 772
hrac 3'RIGHT'
hrac 2'UP'
tah 773
hrac 3'UP'
hrac 2'UP'
tah 774
hrac 3'UP'
hrac 2'UP'
tah 775
hrac 3'LEFT'
hrac 2'UP'
tah 776
hrac 3'UP'
hrac 2'UP'
tah 777
hrac 3'DOWN'
hrac 2'UP'
tah 778
hrac 3'LEFT'
hrac 2'UP'
tah 779
hrac 3'DOWN'
hrac 2'UP'
tah 780
hrac 3'RIGHT'
hrac 2'UP'
tah 781
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 782
hrac 3'UP'
hrac 2'UP'
tah 783
hrac 3'UP'
hrac 2'UP'
tah 784
hrac 3'DOWN'
hrac 2'LEFT'
tah 785
hrac 3'RIGHT'
hrac 2'LEFT'
tah 786
hrac 3'UP'
hrac 2'DOWN'
tah 787
hrac 3'LEFT'
hrac 2'DOWN'
tah 788
hrac 3'UP'
hrac 2'DOWN'
tah 789
hrac 3'DOWN'
hrac 2'DOWN'
tah 790
hrac 3'LEFT'
hrac 2'DOWN'
tah 791
hrac 3'LEFT'
hrac 2'DOWN'
tah 792
hrac 3'RIGHT'
hrac 2'DOWN'
tah 793
hrac 3'UP'
hrac 2'DOWN'
tah 794
hrac 3'DOWN'
hrac 2'DOWN'
tah 795
hrac 3'UP'
hrac 2'DOWN'
tah 796
hrac 3'UP'
hrac 2'DOWN'
tah 797
hrac 3'DOWN'
hrac 2'DOWN'
tah 798
hrac 3'LEFT'
hrac 2'DOWN'
tah 799
hrac 3'RIGHT'
hrac 2'DOWN'
tah 800
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 801
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 802
hrac 3'DOWN'
hrac 2'LEFT'
tah 803
hrac 3'RIGHT'
hrac 2'LEFT'
tah 804
hrac 3'DOWN'
hrac 2'RIGHT'
tah 805
hrac 3'UP'
hrac 2'RIGHT'
tah 806
hrac 3'UP'
hrac 2'LEFT'
tah 807
hrac 3'RIGHT'
hrac 2'LEFT'
tah 808
hrac 3'LEFT'
hrac 2'UP'
tah 809
hrac 3'UP'
hrac 2'UP'
tah 810
hrac 3'DOWN'
hrac 2'UP'
tah 811
hrac 3'LEFT'
hrac 2'UP'
tah 812
hrac 3'UP'
hrac 2'UP'
tah 813
hrac 3'DOWN'
hrac 2'UP'
tah 814
hrac 3'LEFT'
hrac 2'UP'
tah 815
hrac 3'UP'
hrac 2'UP'
tah 816
hrac 3'RIGHT'
hrac 2'UP'
tah 817
hrac 3'UP'
hrac 2'UP'
tah 818
hrac 3'DOWN'
hrac 2'UP'
tah 819
hrac 3'UP'
hrac 2'UP'
tah 820
hrac 3'LEFT'
hrac 2'UP'
tah 821
hrac 3'DOWN'
hrac 2'UP'
tah 822
hrac 3'LEFT'
hrac 2'UP'
tah 823
hrac 3'UP'
hrac 2'UP'
tah 824
hrac 3'RIGHT'
hrac 2'UP'
tah 825
hrac 3'UP'
hrac 2'UP'
tah 826
hrac 3'DOWN'
hrac 2'UP'
tah 827
hrac 3'LEFT'
hrac 2'UP'
tah 828
hrac 3'UP'
hrac 2'UP'
tah 829
hrac 3'DOWN'
hrac 2'UP'
tah 830
hrac 3'LEFT'
hrac 2'UP'
tah 831
hrac 3'RIGHT'
hrac 2'UP'
tah 832
hrac 3'LEFT'
hrac 2'UP'
tah 833
hrac 3'DOWN'
hrac 2'UP'
tah 834
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 835
hrac 3'UP'
hrac 2'RIGHT'
tah 836
hrac 3'UP'
hrac 2'DOWN'
tah 837
hrac 3'LEFT'
hrac 2'DOWN'
tah 838
hrac 3'DOWN'
hrac 2'DOWN'
tah 839
hrac 3'RIGHT'
hrac 2'DOWN'
tah 840
hrac 3'UP'
hrac 2'UP'
tah 841
hrac 3'UP'
hrac 2'UP'
tah 842
hrac 3'DOWN'
hrac 2'UP'
tah 843
hrac 3'UP'
hrac 2'UP'
tah 844
hrac 3'UP'
hrac 2'UP'
tah 845
hrac 3'DOWN'
hrac 2'DOWN'
tah 846
hrac 3'LEFT'
hrac 2'DOWN'
tah 847
hrac 3'RIGHT'
hrac 2'UP'
tah 848
hrac 3'RIGHT'
hrac 2'UP'
tah 849
hrac 3'DOWN'
hrac 2'DOWN'
tah 850
hrac 3'RIGHT'
hrac 2'DOWN'
tah 851
hrac 3'DOWN'
hrac 2'LEFT'
tah 852
hrac 3'UP'
hrac 2'DOWN'
tah 853
hrac 3'UP'
hrac 2'DOWN'
tah 854
hrac 3'DOWN'
hrac 2'DOWN'
tah 855
hrac 3'RIGHT'
hrac 2'DOWN'
tah 856
hrac 3'UP'
hrac 2'DOWN'
tah 857
hrac 3'DOWN'
hrac 2'DOWN'
tah 858
hrac 3'UP'
hrac 2'DOWN'
tah 859
hrac 3'UP'
hrac 2'LEFT'
tah 860
hrac 3'DOWN'
hrac 2'DOWN'
tah 861
hrac 3'LEFT'
hrac 2'LEFT'
tah 862
hrac 3'UP'
hrac 2'DOWN'
tah 863
hrac 3'DOWN'
hrac 2'DOWN'
tah 864
hrac 3'LEFT'
hrac 2'DOWN'
tah 865
hrac 3'UP'
hrac 2'DOWN'
tah 866
hrac 3'DOWN'
hrac 2'DOWN'
tah 867
hrac 3'UP'
hrac 2'DOWN'
tah 868
hrac 3'UP'
hrac 2'DOWN'
tah 869
hrac 3'DOWN'
hrac 2'DOWN'
tah 870
hrac 3'RIGHT'
hrac 2'DOWN'
tah 871
hrac 3'UP'
hrac 2'DOWN'
tah 872
hrac 3'DOWN'
hrac 2'DOWN'
tah 873
hrac 3'RIGHT'
hrac 2'DOWN'
tah 874
hrac 3'UP'
hrac 2'DOWN'
tah 875
hrac 3'DOWN'
hrac 2'DOWN'
tah 876
hrac 3'RIGHT'
hrac 2'DOWN'
tah 877
hrac 3'LEFT'
hrac 2'DOWN'
tah 878
hrac 3'RIGHT'
hrac 2'DOWN'
tah 879
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 880
hrac 3'DOWN'
hrac 2'RIGHT'
tah 881
hrac 3'RIGHT'
hrac 2'LEFT'
tah 882
hrac 3'UP'
hrac 2'LEFT'
tah 883
hrac 3'LEFT'
hrac 2'RIGHT'
tah 884
hrac 3'UP'
hrac 2'RIGHT'
tah 885
hrac 3'DOWN'
hrac 2'RIGHT'
tah 886
hrac 3'RIGHT'
hrac 2'UP'
tah 887
hrac 3'RIGHT'
hrac 2'UP'
tah 888
hrac 3'LEFT'
hrac 2'UP'
tah 889
hrac 3'UP'
hrac 2'UP'
tah 890
hrac 3'DOWN'
hrac 2'LEFT'
tah 891
hrac 3'RIGHT'
hrac 2'DOWN'
tah 892
hrac 3'RIGHT'
hrac 2'DOWN'
tah 893
hrac 3'LEFT'
hrac 2'DOWN'
tah 894
hrac 3'DOWN'
hrac 2'DOWN'
tah 895
hrac 3'UP'
hrac 2'LEFT'
tah 896
hrac 3'UP'
hrac 2'LEFT'
tah 897
hrac 3'LEFT'
hrac 2'RIGHT'
tah 898
hrac 3'UP'
hrac 2'RIGHT'
tah 899
hrac 3'DOWN'
hrac 2'RIGHT'
tah 900
hrac 3'LEFT'
hrac 2'UP'
tah 901
hrac 3'UP'
hrac 2'UP'
tah 902
hrac 3'DOWN'
hrac 2'UP'
tah 903
hrac 3'LEFT'
hrac 2'UP'
tah 904
hrac 3'LEFT'
hrac 2'DOWN'
tah 905
hrac 3'UP'
hrac 2'DOWN'
tah 906
hrac 3'DOWN'
hrac 2'UP'
tah 907
hrac 3'LEFT'
hrac 2'UP'
tah 908
hrac 3'UP'
hrac 2'DOWN'
tah 909
hrac 3'RIGHT'
hrac 2'DOWN'
tah 910
hrac 3'RIGHT'
hrac 2'UP'
tah 911
hrac 3'DOWN'
hrac 2'UP'
tah 912
hrac 3'UP'
hrac 2'DOWN'
tah 913
hrac 3'UP'
hrac 2'DOWN'
tah 914
hrac 3'DOWN'
hrac 2'UP'
tah 915
hrac 3'UP'
hrac 2'UP'
tah 916
hrac 3'LEFT'
hrac 2'UP'
tah 917
hrac 3'DOWN'
hrac 2'UP'
tah 918
hrac 3'LEFT'
hrac 2'DOWN'
tah 919
hrac 3'UP'
hrac 2'DOWN'
tah 920
hrac 3'DOWN'
hrac 2'UP'
tah 921
hrac 3'LEFT'
hrac 2'UP'
tah 922
hrac 3'RIGHT'
hrac 2'UP'
tah 923
hrac 3'LEFT'
hrac 2'UP'
tah 924
hrac 3'LEFT'
hrac 2'UP'
tah 925
hrac 3'RIGHT'
hrac 2'UP'
tah 926
hrac 3'UP'
hrac 2'LEFT'
tah 927
hrac 3'RIGHT'
hrac 2'DOWN'
tah 928
hrac 3'UP'
hrac 2'DOWN'
tah 929
hrac 3'DOWN'
hrac 2'DOWN'
tah 930
hrac 3'LEFT'
hrac 2'DOWN'
tah 931
hrac 3'UP'
hrac 2'DOWN'
tah 932
hrac 3'RIGHT'
hrac 2'DOWN'
tah 933
hrac 3'RIGHT'
hrac 2'DOWN'
tah 934
hrac 3'DOWN'
hrac 2'DOWN'
tah 935
hrac 3'RIGHT'
hrac 2'DOWN'
tah 936
hrac 3'RIGHT'
hrac 2'DOWN'
tah 937
hrac 3'DOWN'
hrac 2'LEFT'
tah 938
hrac 3'RIGHT'
hrac 2'LEFT'
tah 939
hrac 3'RIGHT'
hrac 2'LEFT'
tah 940
hrac 3'LEFT'
hrac 2'LEFT'
tah 941
hrac 3'UP'
hrac 2'LEFT'
tah 942
hrac 3'DOWN'
hrac 2'LEFT'
tah 943
hrac 3'RIGHT'
hrac 2'LEFT'
tah 944
hrac 3'RIGHT'
hrac 2'LEFT'
tah 945
hrac 3'LEFT'
hrac 2'LEFT'
tah 946
hrac 3'UP'
hrac 2'LEFT'
tah 947
hrac 3'DOWN'
hrac 2'LEFT'
tah 948
hrac 3'RIGHT'
hrac 2'LEFT'
tah 949
hrac 3'DOWN'
hrac 2'LEFT'
tah 950
hrac 3'UP'
hrac 2'LEFT'
tah 951
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 952
hrac 3'LEFT'
hrac 2'RIGHT'
tah 953
hrac 3'UP'
hrac 2'RIGHT'
tah 954
hrac 3'DOWN'
hrac 2'RIGHT'
tah 955
hrac 3'DOWN'
hrac 2'LEFT'
tah 956
hrac 3'RIGHT'
hrac 2'LEFT'
tah 957
hrac 3'LEFT'
hrac 2'UP'
tah 958
hrac 3'RIGHT'
hrac 2'UP'
tah 959
hrac 3'RIGHT'
hrac 2'UP'
tah 960
hrac 3'LEFT'
hrac 2'RIGHT'
tah 961
hrac 3'DOWN'
hrac 2'UP'
tah 962
hrac 3'LEFT'
hrac 2'UP'
tah 963
hrac 3'DOWN'
hrac 2'UP'
tah 964
hrac 3'LEFT'
hrac 2'UP'
tah 965
hrac 3'RIGHT'
hrac 2'UP'
tah 966
hrac 3'RIGHT'
hrac 2'UP'
tah 967
hrac 3'UP'
hrac 2'UP'
tah 968
hrac 3'RIGHT'
hrac 2'UP'
tah 969
hrac 3'LEFT'
hrac 2'RIGHT'
tah 970
hrac 3'DOWN'
hrac 2'UP'
tah 971
hrac 3'RIGHT'
hrac 2'UP'
tah 972
hrac 3'UP'
hrac 2'UP'
tah 973
hrac 3'RIGHT'
hrac 2'UP'
tah 974
hrac 3'LEFT'
hrac 2'RIGHT'
tah 975
hrac 3'RIGHT'
hrac 2'UP'
tah 976
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 977
hrac 3'LEFT'
hrac 2'UP'
tah 978
hrac 3'UP'
hrac 2'UP'
tah 979
hrac 3'LEFT'
hrac 2'RIGHT'
tah 980
hrac 3'UP'
hrac 2'UP'
tah 981
hrac 3'DOWN'
hrac 2'UP'
tah 982
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 983
hrac 3'RIGHT'
hrac 2'UP'
tah 984
hrac 3'DOWN'
hrac 2'RIGHT'
tah 985
hrac 3'DOWN'
hrac 2'UP'
tah 986
hrac 3'UP'
hrac 2'RIGHT'
tah 987
hrac 3'RIGHT'
hrac 2'UP'
tah 988
hrac 3'LEFT'
hrac 2'RIGHT'
tah 989
hrac 3'UP'
hrac 2'UP'
tah 990
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 991
hrac 3'DOWN'
hrac 2'UP'
tah 992
hrac 3'RIGHT'
hrac 2'RIGHT'
tah 993
hrac 3'LEFT'
hrac 2'UP'
tah 994
hrac 3'DOWN'
hrac 2'RIGHT'
tah 995
hrac 3'UP'
hrac 2'UP'
tah 996
hrac 3'DOWN'
hrac 2'RIGHT'
tah 997
hrac 3'DOWN'
hrac 2'UP'
tah 998
hrac 3'UP'
hrac 2'UP'
tah 999
hrac 3'RIGHT'
hrac 2'LEFT'
ukoncujem klientov
[21:25:18.165] 
proces 29801 umrel na: Terminated
proces 29802 umrel na: Terminated
