[20:52:25.615] startujem server, seed je 756770824
main: prepisujem zaznamovy adresar: zaznamy/000002
[20:52:25.615] restartujem klienta okno
[20:52:25.615] restartujem klienta nahodicka
[20:52:25.615] restartujem klienta nulano
[20:52:25.615] restartujem klienta veduci
tah 0
hrac 0'DOWN'
hrac 1'UP'
hrac 2'DOWN'
hrac 3'LEFT'
tah 1
hrac 1'UP'
hrac 2'DOWN'
hrac 0'DOWN'
hrac 3'LEFT'
tah 2
hrac 1'LEFT'
hrac 2'UP'
hrac 0'RIGHT'
hrac 3'LEFT'
tah 3
hrac 1'LEFT'
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'UP'
tah 4
hrac 1'DOWN'
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'UP'
tah 5
hrac 1'DOWN'
hrac 2'UP'
hrac 3'LEFT'
hrac 0'RIGHT'
tah 6
hrac 1'RIGHT'
hrac 2'LEFT'
hrac 3'DOWN'
hrac 0'DOWN'
tah 7
hrac 1'UP'
hrac 2'UP'
hrac 3'RIGHT'
hrac 0'DOWN'
tah 8
hrac 1'UP'
hrac 2'LEFT'
hrac 3'RIGHT'
hrac 0'LEFT'
tah 9
hrac 1'UP'
hrac 2'RIGHT'
hrac 3'RIGHT'
hrac 0'LEFT'
tah 10
hrac 1'LEFT'
hrac 2'DOWN'
hrac 3'RIGHT'
hrac 0'RIGHT'
tah 11
hrac 1'LEFT'
hrac 2'DOWN'
hrac 3'RIGHT'
hrac 0'DOWN'
tah 12
hrac 1'DOWN'
hrac 2'RIGHT'
hrac 3'LEFT'
hrac 0'UP'
tah 13
hrac 1'DOWN'
hrac 2'DOWN'
hrac 3'DOWN'
hrac 0'UP'
tah 14
hrac 1'RIGHT'
hrac 2'UP'
hrac 3'DOWN'
hrac 0'UP'
tah 15
hrac 1'UP'
hrac 2'RIGHT'
hrac 3'DOWN'
hrac 0'UP'
tah 16
hrac 1'UP'
hrac 2'LEFT'
hrac 3'DOWN'
hrac 0'UP'
tah 17
hrac 1'UP'
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'DOWN'
tah 18
hrac 1'LEFT'
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'DOWN'
tah 19
hrac 1'LEFT'
hrac 2'UP'
hrac 3'LEFT'
hrac 0'UP'
tah 20
hrac 1'DOWN'
hrac 2'LEFT'
hrac 3'LEFT'
hrac 0'UP'
tah 21
hrac 1'DOWN'
hrac 2'RIGHT'
hrac 3'LEFT'
hrac 0'DOWN'
tah 22
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 3'LEFT'
hrac 0'DOWN'
tah 23
hrac 1'UP'
hrac 2'LEFT'
hrac 3'LEFT'
hrac 0'DOWN'
tah 24
hrac 1'UP'
hrac 2'LEFT'
hrac 3'LEFT'
hrac 0'DOWN'
tah 25
hrac 1'UP'
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'DOWN'
tah 26
hrac 1'LEFT'
hrac 2'RIGHT'
hrac 3'UP'
hrac 0'RIGHT'
tah 27
hrac 1'LEFT'
hrac 2'DOWN'
hrac 3'RIGHT'
hrac 0'DOWN'
tah 28
hrac 1'DOWN'
hrac 2'UP'
hrac 3'RIGHT'
hrac 0'LEFT'
tah 29
hrac 1'DOWN'
hrac 2'RIGHT'
hrac 3'RIGHT'
hrac 0'UP'
hrac 0 bol zabity hracom 3
proces 28233 umrel na: Terminated
write: pid -1: Bad file descriptor
tah 30
hrac 2'LEFT'
hrac 1'RIGHT'
hrac 3'UP'
tah 31
hrac 2'RIGHT'
hrac 1'UP'
hrac 3'UP'
tah 32
hrac 2'DOWN'
hrac 1'DOWN'
hrac 3'LEFT'
tah 33
hrac 2'UP'
hrac 1'DOWN'
hrac 3'UP'
tah 34
hrac 2'RIGHT'
hrac 1'RIGHT'
hrac 3'RIGHT'
tah 35
hrac 2'UP'
hrac 1'RIGHT'
hrac 3'RIGHT'
tah 36
hrac 2'RIGHT'
hrac 1'UP'
hrac 3'RIGHT'
tah 37
hrac 2'LEFT'
hrac 1'UP'
hrac 3'RIGHT'
tah 38
hrac 2'RIGHT'
hrac 1'LEFT'
hrac 3'UP'
tah 39
hrac 2'RIGHT'
hrac 1'DOWN'
hrac 3'UP'
tah 40
hrac 2'LEFT'
hrac 1'DOWN'
hrac 3'UP'
tah 41
hrac 2'DOWN'
hrac 1'DOWN'
hrac 3'UP'
tah 42
hrac 1'RIGHT'
hrac 2'UP'
hrac 3'LEFT'
tah 43
hrac 2'UP'
hrac 1'RIGHT'
hrac 3'UP'
tah 44
hrac 2'DOWN'
hrac 1'UP'
hrac 3'LEFT'
tah 45
hrac 2'DOWN'
hrac 1'UP'
hrac 3'UP'
tah 46
hrac 2'DOWN'
hrac 1'LEFT'
hrac 3'LEFT'
tah 47
hrac 2'UP'
hrac 1'DOWN'
hrac 3'UP'
tah 48
hrac 2'RIGHT'
hrac 1'DOWN'
hrac 3'UP'
tah 49
hrac 2'UP'
hrac 1'DOWN'
hrac 3'UP'
tah 50
hrac 2'UP'
hrac 1'RIGHT'
hrac 3'UP'
tah 51
hrac 2'LEFT'
hrac 1'RIGHT'
hrac 3'UP'
hrac 3 bol zabity hracom 1
proces 28236 umrel na: Terminated
write: pid -1: Bad file descriptor
tah 52
hrac 2'UP'
hrac 1'UP'
tah 53
hrac 2'LEFT'
hrac 1'UP'
tah 54
hrac 2'UP'
hrac 1'LEFT'
tah 55
hrac 2'DOWN'
hrac 1'DOWN'
tah 56
hrac 2'RIGHT'
hrac 1'DOWN'
tah 57
hrac 1'DOWN'
hrac 2'RIGHT'
tah 58
hrac 2'LEFT'
hrac 1'LEFT'
tah 59
hrac 2'UP'
hrac 1'LEFT'
tah 60
hrac 2'LEFT'
hrac 1'UP'
tah 61
hrac 2'UP'
hrac 1'UP'
tah 62
hrac 2'DOWN'
hrac 1'RIGHT'
tah 63
hrac 2'UP'
hrac 1'DOWN'
tah 64
hrac 2'RIGHT'
hrac 1'DOWN'
tah 65
hrac 2'LEFT'
hrac 1'DOWN'
tah 66
hrac 1'LEFT'
hrac 2'RIGHT'
tah 67
hrac 2'UP'
hrac 1'LEFT'
tah 68
hrac 2'DOWN'
hrac 1'UP'
tah 69
hrac 2'RIGHT'
hrac 1'UP'
tah 70
hrac 2'LEFT'
hrac 1'RIGHT'
tah 71
hrac 2'RIGHT'
hrac 1'DOWN'
tah 72
hrac 2'UP'
hrac 1'DOWN'
tah 73
hrac 2'LEFT'
hrac 1'DOWN'
tah 74
hrac 2'UP'
hrac 1'LEFT'
tah 75
hrac 2'DOWN'
hrac 1'LEFT'
hrac 1 narazil do okraja mapy
proces 28234 umrel na: Terminated
write: pid -1: Bad file descriptor
tah 76
hrac 2'RIGHT'
tah 77
hrac 2'UP'
tah 78
hrac 2'LEFT'
tah 79
hrac 2'UP'
tah 80
hrac 2'DOWN'
tah 81
hrac 2'UP'
tah 82
hrac 2'LEFT'
tah 83
hrac 2'RIGHT'
ukoncujem klientov
[20:52:30.381] 
