[21:13:56.906] startujem server, seed je 1794549276
main: prepisujem zaznamovy adresar: zaznamy/000004
[21:13:56.907] restartujem klienta paulinia
[21:13:56.907] restartujem klienta m
[21:13:56.907] restartujem klienta okno
[21:13:56.908] restartujem klienta nulano
tah 0
hrac 0'UP'
hrac 1'LEFT'
hrac 2'DOWN'
hrac 3'RIGHT'
tah 1
hrac 1'LEFT'
hrac 2'DOWN'
hrac 0'UP'
hrac 3'RIGHT'
tah 2
hrac 3'LEFT'
hrac 2'LEFT'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 3
hrac 3'DOWN'
hrac 2'LEFT'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 4
hrac 3'RIGHT'
hrac 2'UP'
hrac 1'UP'
hrac 0'DOWN'
tah 5
hrac 3'UP'
hrac 2'RIGHT'
hrac 1'UP'
hrac 0'DOWN'
tah 6
hrac 1'RIGHT'
hrac 2'RIGHT'
hrac 3'UP'
hrac 0'DOWN'
tah 7
hrac 1'RIGHT'
hrac 2'UP'
hrac 3'DOWN'
hrac 0'RIGHT'
tah 8
hrac 1'RIGHT'
hrac 2'UP'
hrac 3'DOWN'
hrac 0'RIGHT'
tah 9
hrac 1'RIGHT'
hrac 2'UP'
hrac 3'RIGHT'
hrac 0'DOWN'
tah 10
hrac 1'DOWN'
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'DOWN'
tah 11
hrac 1'DOWN'
hrac 2'DOWN'
hrac 3'DOWN'
hrac 0'DOWN'
tah 12
hrac 1'LEFT'
hrac 2'UP'
hrac 3'UP'
hrac 0'RIGHT'
tah 13
hrac 1'RIGHT'
hrac 2'UP'
hrac 3'DOWN'
hrac 0'UP'
tah 14
hrac 1'RIGHT'
hrac 2'DOWN'
hrac 3'DOWN'
hrac 0'UP'
tah 15
hrac 1'LEFT'
hrac 2'DOWN'
hrac 3'UP'
hrac 0'UP'
tah 16
hrac 1'DOWN'
hrac 2'UP'
hrac 3'LEFT'
hrac 0'UP'
tah 17
hrac 1'LEFT'
hrac 2'UP'
hrac 3'RIGHT'
hrac 0'LEFT'
tah 18
hrac 1'LEFT'
hrac 2'DOWN'
hrac 0'DOWN'
hrac 3'DOWN'
tah 19
hrac 1'DOWN'
hrac 2'DOWN'
hrac 3'DOWN'
hrac 0'DOWN'
tah 20
hrac 1'UP'
hrac 2'UP'
hrac 3'UP'
hrac 0'LEFT'
tah 21
hrac 1'UP'
hrac 2'UP'
hrac 3'RIGHT'
hrac 0'LEFT'
tah 22
hrac 1'RIGHT'
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'DOWN'
tah 23
hrac 1'RIGHT'
hrac 2'DOWN'
hrac 3'DOWN'
hrac 0'DOWN'
tah 24
hrac 1'DOWN'
hrac 3'RIGHT'
hrac 0'RIGHT'
hrac 2'UP'
tah 25
hrac 1'DOWN'
hrac 3'UP'
hrac 2'UP'
hrac 0'RIGHT'
tah 26
hrac 1'UP'
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'RIGHT'
tah 27
hrac 1'DOWN'
hrac 2'DOWN'
hrac 3'DOWN'
hrac 0'RIGHT'
tah 28
hrac 1'RIGHT'
hrac 2'UP'
hrac 3'DOWN'
hrac 0'UP'
tah 29
hrac 1'RIGHT'
hrac 2'UP'
hrac 3'UP'
hrac 0'UP'
tah 30
hrac 1'DOWN'
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'UP'
tah 31
hrac 1'DOWN'
hrac 2'DOWN'
hrac 3'RIGHT'
hrac 0'UP'
tah 32
hrac 1'LEFT'
hrac 2'UP'
hrac 3'DOWN'
hrac 0'LEFT'
tah 33
hrac 1'LEFT'
hrac 2'UP'
hrac 3'LEFT'
hrac 0'UP'
tah 34
hrac 1'LEFT'
hrac 2'DOWN'
hrac 3'UP'
hrac 0'UP'
tah 35
hrac 1'LEFT'
hrac 2'DOWN'
hrac 3'DOWN'
hrac 0'UP'
tah 36
hrac 1'LEFT'
hrac 2'UP'
hrac 3'LEFT'
hrac 0'LEFT'
tah 37
hrac 1'UP'
hrac 2'UP'
hrac 3'RIGHT'
hrac 0'LEFT'
tah 38
hrac 1'LEFT'
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'LEFT'
tah 39
hrac 1'LEFT'
hrac 2'DOWN'
hrac 3'LEFT'
hrac 0'UP'
tah 40
hrac 3'RIGHT'
hrac 2'UP'
hrac 1'LEFT'
hrac 0'UP'
tah 41
hrac 3'LEFT'
hrac 2'UP'
hrac 1'UP'
hrac 0'LEFT'
tah 42
hrac 3'UP'
hrac 2'DOWN'
hrac 1'UP'
hrac 0'LEFT'
tah 43
hrac 3'DOWN'
hrac 2'DOWN'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 44
hrac 3'LEFT'
hrac 2'UP'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 45
hrac 3'RIGHT'
hrac 2'UP'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 46
hrac 3'UP'
hrac 2'DOWN'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 47
hrac 3'LEFT'
hrac 2'DOWN'
hrac 1'RIGHT'
hrac 0'UP'
tah 48
hrac 3'DOWN'
hrac 2'DOWN'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 49
hrac 3'LEFT'
hrac 2'DOWN'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 50
hrac 3'RIGHT'
hrac 2'RIGHT'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 51
hrac 3'UP'
hrac 2'LEFT'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 52
hrac 3'UP'
hrac 2'LEFT'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 53
hrac 3'DOWN'
hrac 2'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
tah 54
hrac 3'LEFT'
hrac 2'LEFT'
hrac 1'LEFT'
hrac 0'DOWN'
tah 55
hrac 3'DOWN'
hrac 2'DOWN'
hrac 1'DOWN'
hrac 0'RIGHT'
tah 56
hrac 3'LEFT'
hrac 2'RIGHT'
hrac 1'DOWN'
hrac 0'UP'
tah 57
hrac 3'RIGHT'
hrac 2'UP'
hrac 1'DOWN'
hrac 0'UP'
tah 58
hrac 3'LEFT'
hrac 2'UP'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 59
hrac 3'UP'
hrac 2'DOWN'
hrac 1'RIGHT'
hrac 0'DOWN'
tah 60
hrac 3'RIGHT'
hrac 2'DOWN'
hrac 1'LEFT'
hrac 0'DOWN'
tah 61
hrac 3'UP'
hrac 2'DOWN'
hrac 1'RIGHT'
hrac 0'DOWN'
tah 62
hrac 3'DOWN'
hrac 2'UP'
hrac 1'DOWN'
hrac 0'DOWN'
tah 63
hrac 3'LEFT'
hrac 2'UP'
hrac 1'UP'
hrac 0'UP'
tah 64
hrac 3'LEFT'
hrac 2'DOWN'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 65
hrac 3'RIGHT'
hrac 2'DOWN'
hrac 1'LEFT'
hrac 0'UP'
tah 66
hrac 3'UP'
hrac 2'DOWN'
hrac 1'UP'
hrac 0'LEFT'
tah 67
hrac 3'DOWN'
hrac 2'RIGHT'
hrac 1'UP'
hrac 0'UP'
tah 68
hrac 3'DOWN'
hrac 2'DOWN'
hrac 1'DOWN'
hrac 0'RIGHT'
tah 69
hrac 3'LEFT'
hrac 2'LEFT'
hrac 1'UP'
hrac 0'DOWN'
tah 70
hrac 3'RIGHT'
hrac 2'DOWN'
hrac 1'UP'
hrac 0'RIGHT'
tah 71
hrac 3'UP'
hrac 2'RIGHT'
hrac 1'UP'
hrac 0'UP'
tah 72
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'UP'
hrac 2 narazil do steny
proces 29226 umrel na: Terminated
tah 73
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'LEFT'
tah 74
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'LEFT'
tah 75
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'UP'
tah 76
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'DOWN'
tah 77
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'UP'
tah 78
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 79
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'DOWN'
tah 80
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'UP'
tah 81
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'RIGHT'
tah 82
hrac 3'UP'
hrac 1'LEFT'
hrac 0'DOWN'
tah 83
hrac 3'DOWN'
hrac 1'UP'
hrac 0'RIGHT'
tah 84
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'UP'
tah 85
hrac 3'LEFT'
hrac 1'UP'
hrac 0'UP'
tah 86
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'LEFT'
tah 87
hrac 3'UP'
hrac 1'LEFT'
hrac 0'LEFT'
tah 88
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'LEFT'
tah 89
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'DOWN'
tah 90
hrac 1'UP'
hrac 3'LEFT'
hrac 0'LEFT'
tah 91
hrac 1'UP'
hrac 3'RIGHT'
hrac 0'LEFT'
tah 92
hrac 1'LEFT'
hrac 3'UP'
hrac 0'DOWN'
tah 93
hrac 1'LEFT'
hrac 3'RIGHT'
hrac 0'LEFT'
tah 94
hrac 3'UP'
hrac 1'LEFT'
hrac 0'DOWN'
tah 95
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'UP'
tah 96
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 97
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'UP'
tah 98
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'UP'
tah 99
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 100
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'LEFT'
tah 101
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'LEFT'
tah 102
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'LEFT'
tah 103
hrac 3'DOWN'
hrac 1'UP'
hrac 0'DOWN'
tah 104
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'DOWN'
tah 105
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 106
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'DOWN'
tah 107
hrac 3'UP'
hrac 1'DOWN'
hrac 0'DOWN'
tah 108
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'DOWN'
tah 109
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 110
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 111
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'LEFT'
tah 112
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 113
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'UP'
tah 114
hrac 3'LEFT'
hrac 1'UP'
hrac 0'RIGHT'
tah 115
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'RIGHT'
tah 116
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'DOWN'
tah 117
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'DOWN'
tah 118
hrac 3'UP'
hrac 1'UP'
hrac 0'LEFT'
tah 119
hrac 3'UP'
hrac 1'UP'
hrac 0'LEFT'
tah 120
hrac 3'DOWN'
hrac 1'UP'
hrac 0'DOWN'
tah 121
hrac 3'UP'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 122
hrac 3'UP'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 123
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 124
hrac 3'LEFT'
hrac 0'UP'
hrac 1'DOWN'
tah 125
hrac 1'LEFT'
hrac 3'RIGHT'
hrac 0'UP'
tah 126
hrac 1'LEFT'
hrac 3'LEFT'
hrac 0'UP'
tah 127
hrac 1'DOWN'
hrac 3'UP'
hrac 0'UP'
tah 128
hrac 1'RIGHT'
hrac 3'DOWN'
hrac 0'DOWN'
tah 129
hrac 1'UP'
hrac 3'LEFT'
hrac 0'UP'
tah 130
hrac 1'UP'
hrac 3'RIGHT'
hrac 0'RIGHT'
tah 131
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'RIGHT'
tah 132
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'LEFT'
tah 133
hrac 3'UP'
hrac 1'UP'
hrac 0'RIGHT'
tah 134
hrac 3'UP'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 135
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 136
hrac 3'UP'
hrac 1'LEFT'
hrac 0'UP'
tah 137
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 138
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'LEFT'
tah 139
hrac 3'UP'
hrac 1'DOWN'
hrac 0'UP'
tah 140
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 141
hrac 3'RIGHT'
hrac 1'UP'
hrac 0'LEFT'
tah 142
hrac 3'LEFT'
hrac 1'UP'
hrac 0'UP'
tah 143
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'UP'
tah 144
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'LEFT'
tah 145
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 146
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 147
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'LEFT'
tah 148
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'UP'
tah 149
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'UP'
tah 150
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 151
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 152
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 153
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 154
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 155
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 156
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 157
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'DOWN'
tah 158
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'DOWN'
tah 159
hrac 3'UP'
hrac 1'LEFT'
hrac 0'DOWN'
tah 160
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'UP'
tah 161
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 162
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'DOWN'
tah 163
hrac 3'UP'
hrac 1'UP'
hrac 0'LEFT'
tah 164
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 165
hrac 3'DOWN'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 166
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'RIGHT'
tah 167
hrac 3'LEFT'
hrac 1'LEFT'
hrac 0'DOWN'
tah 168
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'DOWN'
tah 169
hrac 3'RIGHT'
hrac 1'LEFT'
hrac 0'LEFT'
tah 170
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'DOWN'
tah 171
hrac 3'UP'
hrac 1'DOWN'
hrac 0'LEFT'
tah 172
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'DOWN'
tah 173
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'DOWN'
tah 174
hrac 3'UP'
hrac 1'DOWN'
hrac 0'DOWN'
tah 175
hrac 3'RIGHT'
hrac 1'DOWN'
hrac 0'DOWN'
tah 176
hrac 3'DOWN'
hrac 1'DOWN'
hrac 0'LEFT'
tah 177
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'UP'
tah 178
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'UP'
tah 179
hrac 1'RIGHT'
hrac 3'LEFT'
hrac 0'RIGHT'
tah 180
hrac 3'UP'
hrac 1'UP'
hrac 0'RIGHT'
tah 181
hrac 3'DOWN'
hrac 1'UP'
hrac 0'UP'
tah 182
hrac 3'UP'
hrac 1'UP'
hrac 0'RIGHT'
tah 183
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'UP'
tah 184
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 185
hrac 3'UP'
hrac 1'RIGHT'
hrac 0'UP'
tah 186
hrac 3'LEFT'
hrac 1'UP'
hrac 0'LEFT'
tah 187
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'RIGHT'
tah 188
hrac 3'LEFT'
hrac 1'RIGHT'
hrac 0'LEFT'
tah 189
hrac 3'LEFT'
hrac 1'UP'
hrac 0'UP'
tah 190
hrac 3'RIGHT'
hrac 1'RIGHT'
hrac 0'DOWN'
tah 191
hrac 3'LEFT'
hrac 1'DOWN'
hrac 0'RIGHT'
tah 192
hrac 3'UP'
hrac 1'DOWN'
hrac 0'DOWN'
tah 193
hrac 3'DOWN'
hrac 1'RIGHT'
hrac 0'UP'
hrac 3 bol zabity hracom 0
hrac 0 bol zabity hracom 3
proces 29224 umrel na: Terminated
proces 29227 umrel na: Terminated
write: pid -1: Bad file descriptor
write: pid -1: Bad file descriptor
tah 194
hrac 1'DOWN'
tah 195
hrac 1'DOWN'
tah 196
hrac 1'RIGHT'
tah 197
hrac 1'RIGHT'
tah 198
hrac 1'RIGHT'
tah 199
hrac 1'RIGHT'
tah 200
hrac 1'LEFT'
tah 201
hrac 1'DOWN'
ukoncujem klientov
[21:14:07.430] 
